pybossa/cache/users.py
pybossa/view/account.py

- users can update their settings with restrict on/off

fix issues

---

pybossa/util.py
pybossa/view/account.py
pybossa/view/projects.py
test/test_util.py
test/test_web.py

When the redirect URL is a query parameter and we should be redirecting to our own server, ensure that we are.

CROWD-1236 redirect to own server

---

pybossa/syncer/__init__.py
pybossa/syncer/category_syncer.py
pybossa/syncer/project_syncer.py

Use auth header for sync. Tests will come

project sync - use auth

---

pybossa/util.py
pybossa/view/admin.py
test/test_admin.py

All Platforms - when admin adds an admin, all admins should get email

RDISCROWD-1276 Admins emails

---

pybossa/util.py

Fix emails

---

pybossa/exporter/export_helpers.py
test/test_exporter/test_task_csv_exporter.py

Add gold_answers info into task and task_run report
https://jira4.prod.bloomberg.com/browse/RDISCROWD-1305?filter=-1

RDISCROWD-1305 Add gold_answers info into task and task_run report

---

pybossa/cache/task_browse_helpers.py
pybossa/exporter/task_csv_export.py

Re-use the same function for all reports

Re-use the same function for all reports

---

pybossa/view/projects.py

Removed update_blogpost.html and use update_blogpost.html
Update Theme repo

Fix blog update

---

pybossa/exporter/task_csv_export.py
test/test_exporter/test_task_csv_exporter.py
test/test_jobs/test_export_tasks.py

Now Info is flatten before it goes to the csv row formatter func.

Flatten list values

---

pybossa/cloud_store_api/s3.py
pybossa/importers/importer.py
pybossa/jobs.py
pybossa/util.py
pybossa/view/projects.py
test/test_cloud_store_api/test_s3_uploader.py
test/test_importers/test_localCSV_importer.py
test/test_jobs/test_import_tasks.py
test/test_web.py

Crowd 1442 csv fixes

---

test/test_cache/test_cache_projects.py
test/test_forms.py
test/test_view/test_user_import.py
test/test_web.py

There is mock-related code in some tests that doesn't actually do anything. We should remove that.

Fix test: Remove unneeded code.

---

pybossa/api/__init__.py
pybossa/api/task.py
pybossa/importers/csv.py
pybossa/importers/importer.py
pybossa/task_creator_helper.py
pybossa/view/projects.py
test/test_importers/__init__.py
test/test_importers/test_localCSV_importer.py
test/test_web.py

ThIs PR is not complete. Test is missing. Before doing test I . want to get feedback or question about it.
This PR is to standardize how we store gold_ans for public and priv . 
For public Gig gold_answers ={...all answers}
For priv GIG gold_answers ={gold_ans_url: "File that has gold_answers as a JSON"}

Rdiscrowd 1536 2

---

pybossa/view/projects.py
test/test_view/test_project_answer_field_config.py

Changed theme/default submodule and variable name for consistency

change variable name - tie_break_config -> consensus_config

---

settings_local.py.tmpl

- Removed the following Task Presenter templates:
- Image Pattern Recognition
- Sound Pattern Recognition
- Video Pattern Recognition
- Geo-coding
- Transcribing documents
- Added readme files to the directories.
Reference:
https://github.com/bloomberg/pybossa-default-theme/pull/119

RDISCROWD-1581: Removed templates

---

setup.py

Update SQLAlchemy version

---

pybossa/forms/forms.py

- Removed extraneous `ROUND_UP` which is already the default behavior.

RDISCROWD-1670 Cleanup

---

pybossa/syncer/project_syncer.py

- Added GitHub commit message to push details
Ref https://github.com/bloomberg/pybossa-default-theme/pull/144

RDISCROWD-1694 GitHub push details for commit message

---

pybossa/jobs.py
pybossa/view/admin.py
test/test_admin.py
test/test_jobs/test_admin_export_users.py

*Issue number of the reported bug or feature request: RDISCROWD-1708
Moved user export to a background job; results are delivered via email

User export job

---

pybossa/jobs.py
pybossa/view/admin.py
test/test_jobs/test_admin_export_users.py

Change name of function so it does not conflict with the view function name

change function name

---

pybossa/syncer/project_syncer.py

- Updated themes/default.
Ref https://github.com/bloomberg/pybossa-default-theme/pull/148

RDISCROWD-1694 Update themes

---

pybossa/cache/users.py

Removed inefficient subqueries

Simplify query

---

pybossa/cache/users.py
pybossa/view/account.py
test/test_cache/test_cache_users.py
test/test_web.py

*Issue number of the reported bug or feature request: #1595*
1. Created a function that shows the number of tasks that a user has completed in a time interval.
2. Created an endpoint where that function can be called (for the user profile.
1. Tested locally
2. Wrote some unit tests.

crowd-1595 recent tasks

---

pybossa/view/projects.py
test/test_json/test_project.py

Rdiscrowd 1528 remove warning

---

pybossa/jobs.py

*Issue number of the reported bug or feature request: RDISCROWD-1629
Create a fake request context to generate relative urls for file uploads 
Tested locally

s3 upload in background job - create fake request context

---

test/test_quiz_mode.py
test/test_web.py

*Issue number of the reported bug or feature request: #RDISCROWD-1815*
Add unit test for quiz completion mode config setting.
Unit tests

Add unit tests for quiz completion mode.

---

pybossa/view/projects.py

*Issue number of the reported bug or feature request: #RDISCROWD-1476*
We do not want worker co-owners to be able to tell which tasks are gold tasks. So in the task browse screen we need to hide any information that would give that away. Hiding the task redundancy, % complete, and Gold columns does that, along with removing gold_answers from results.json.
We probably still need to modify the downloaded reports to hide the gold info.
Manual testing with a worker co-owner account I created.

Hide gold task info for worker co-owners.

---

pybossa/api/api_base.py
pybossa/api/task_run.py
pybossa/repositories/__init__.py
test/test_api/test_taskrun_api.py

Modify task run api get call so that it can filter records based on date range that can be applied against task run finish time.
manual, unit test

filter task runs by date range on finish time

---

pybossa/exporter/consensus_exporter.py
pybossa/exporter/export_helpers.py
pybossa/exporter/task_csv_export.py
pybossa/exporter/task_json_export.py
pybossa/jobs.py
pybossa/view/projects.py
test/test_exporter/test_task_csv_exporter.py
test/test_jobs/test_export.py
test/test_jobs/test_export_tasks.py

*Issue number of the reported bug or feature request: #RDISCROWD-1914*
For worker co-owners, remove information from reports that could be used to identify which tasks are gold.
Manual

Remove task gold info from reports.

---

pybossa/api/__init__.py
pybossa/service_validators.py
setup.py
test/test_service_validators.py
test/test_web.py

*Issue number of the reported bug or feature request: Rdiscrowd 1637*
New Api that will allow the project owners to call a service
Unit test

Rdiscrowd 1637 proxy

---

pybossa/sched.py
test/test_locked_sched.py
test/test_quiz_mode.py

There is a bug with the behavior that when there are only gold tasks are left, and that task has more answers than redundancy, the task is not scheduled.  Here we fix the problem but also refactor some of the code to make it easier to reason.
I will add some unit test(s) to test the case being fixed here.

CROWD-1903 Refactor locked task scheduler code

---

pybossa/view/projects.py

*Issue number of the reported bug or feature request: #RDISCROWD-1983*
Show %Complete in task browse table for vendor co-owners.
Manual

Restore % complete field in task browse for vendors

---

pybossa/cache/users.py
pybossa/view/account.py
test/test_web.py

We need to clear the get_user_by_id function.

user pref cache fix

---

pybossa/forms/forms.py
pybossa/sched.py
pybossa/view/projects.py
test/helper/web.py
test/test_quiz_mode.py

*Issue number of the reported bug or feature request: #RDISCROWD-1872*
Add annotation attributes to project update form.
Manual

Add annotation fields to project.

---

pybossa/core.py

*Jira RDISCROWD-1873*
Can we provide a simple text input box (actually similar to e.g. the one that is used to write this description here in JIRA) that allows basic formatting of text

Add section for annotation guidelines and js asset for the library used

---

pybossa/wizard.py
test/test_wizard.py

Wizard update to take in consideration the guidelines.
Also refactor wizard.py

Rdiscrowd 1898

---

pybossa/forms/forms.py
pybossa/view/projects.py
test/test_auditlog.py
test/test_web.py

*Issue number of the reported bug or feature request: Rdiscrowd 1976*
Add update function for annotations guidelines

Rdiscrowd 1976

---

pybossa/importers/csv.py
test/test_importers/test_localCSV_importer.py

*Issue number of the reported bug or feature request: #RDISCROWD-2027*
Support typed fields for CSV import instead of making everything a string.
Added unit tests for coercing to correct type and raising error on type mismatch.

Support typed import fields.

---

pybossa/core.py

Add blpstrap3 css

---

pybossa/syncer/__init__.py
pybossa/syncer/project_syncer.py
pybossa/view/projects.py
test/test_syncer/test_project_syncer.py
test/test_web.py

Initial commit, missing test

---

test/test_api/test_api_common.py
test/test_syncer/test_project_syncer.py

Added test for new logic added when sync a project

Test for sync

---

pybossa/util.py
pybossa/view/projects.py
test/test_view/test_project_summary.py
test/test_web.py

*Jira Issue*
https://jira4.prod.bloomberg.com/browse/RDISCROWD-1575
- created a summary page to allow users to view current configuration and update them without leaving the page. Rewrote all forms in Vue and added a function in project.py to interact with  front-end

project summary page

---

pybossa/api/__init__.py
pybossa/api/api_base.py
pybossa/api/auditlog.py
pybossa/auth/auditlog.py
pybossa/repositories/__init__.py
test/test_api/test_auditlog_api.py

Added a new api for auditlogs and added support for created_from and created_to for all api

Added a new api to get logs

---

pybossa/cloud_store_api/s3.py
pybossa/view/fileproxy.py
test/test_view/test_fileproxy.py

Allow per project encryption when proxying from S3, allowing project owners to bring their own buckets

Bucket read

---

pybossa/view/fileproxy.py
test/test_view/test_fileproxy.py

The tests pass locally.  I am also able to access the file locally.  But I am getting a 403 from QA.  Some extra logging around the valid file check.

extra hdfs logging

---

pybossa/importers/importer.py
pybossa/task_creator_helper.py
pybossa/util.py
test/test_task_creator_helpers.py

do not compare datetime and str

---

pybossa/model/completion_event.py
pybossa/model/event_listeners.py
test/test_model/test_model_base.py

mark tasks as completed regardless of project status

---

pybossa/api/__init__.py

apply signature for gold tasks

---

pybossa/data_access.py
test/test_data_access.py
test/test_web.py
test/test_wizard.py

Remove the check for tracking_id since it is no longer required (or collected).

crowd-1557 remove tracking id

---

pybossa/forms/forms.py
test/test_view/test_annotations.py

*Issue number of the reported bug or feature request: #RDISCROWD-2230
Change sampling_method from free text to enumerated drop-down
Manual

Make sampling_method a dropdown.

---

pybossa/forms/forms.py
test/test_view/test_annotations.py

dropdown for sampling method under annotation

dropdown for sampling method

---

pybossa/view/projects.py

https://github.com/lepture/flask-wtf/commit/42befd0420d1f4896a70339de3d474044461a1c9#diff-069d3a12d01a20991093d271171e770dL165
https://github.com/inveniosoftware/invenio-communities/issues/102

fix flask wtf crsf token issue 102

---

pybossa/cache/__init__.py

import cache config from app_settings

---

pybossa/cache/projects.py
pybossa/repositories/task_repository.py
test/test_web.py

clear cache when deleting tasks

---

pybossa/view/admin.py

*Issue number of the reported bug or feature request: #<2245>*
Increase timeout waiting time when enqueue the job 
Tested manually by sleeping background worker and check timeout exception

fix timeout when export users in private

---

pybossa/syncer/project_syncer.py

sync guidelines

---

pybossa/forms/forms.py
test/test_view/test_annotations.py

*Issue number of the reported bug or feature request: #RDISCROWD-2370*
Changed "label aggregation strategy" text field to a dropdown
Manual

Make label aggregation strategy an enum.

---

pybossa/model/project.py
pybossa/model/user.py
pybossa/view/projects.py
test/test_quiz_mode.py
test/test_web.py

Rdiscrowd 2114

---

test/test_web.py

Add unit test when an exeption occurr in quiz mode

---

pybossa/core.py
pybossa/view/projects.py

add some logging on error handlers

---

pybossa/api/__init__.py
test/test_web.py

Allow taskgold endpoint upload files from form

---

pybossa/repositories/task_repository.py

reset task status to ongoing

---

test/test_admin.py

RDISCROWD-2453

---

pybossa/forms/dynamic_forms.py
pybossa/forms/forms.py
pybossa/forms/projects_view_forms.py
pybossa/view/projects.py
test/test_view/test_project_clone.py

Add clone form

---

pybossa/forms/forms.py
pybossa/view/projects.py

Move form definition and edit password placeholder

---

pybossa/forms/dynamic_forms.py
pybossa/forms/forms.py
pybossa/view/projects.py

- Sorted products/subproducts drop-down.

RDISCROWD-2234 Project form field validation and styling

---

pybossa/util.py

- Corrected error messages for password minimum and maximum length.

RDISCROWD-2234 password length

---

pybossa/cache/helpers.py
pybossa/cache/projects.py
pybossa/view/projects.py
test/test_cache/test_cache_helpers.py

*Issue number of the reported bug or feature request: #<2441>*

add new field on project-info page.

---

pybossa/view/projects.py
test/test_view/test_project_clone.py

Fix clone owners

---

pybossa/api/__init__.py

Fixed typo.

---

test/test_syncer/__init__.py

Cover syncer

---

pybossa/auth/project.py
pybossa/view/projects.py
pybossa/wizard.py
test/test_auditlog.py
test/test_authorization/test_project_auth.py
test/test_syncer/__init__.py
test/test_view/test_project_publish.py
test/test_web.py
test/test_wizard.py

Rdiscrowd 2591

---

setup.py

fix coverage

---

pybossa/service_validators.py
setup.py

Remove regex dependency

---

pybossa/cache/projects.py
pybossa/cache/users.py
pybossa/exporter/__init__.py
pybossa/exporter/csv_reports_export.py
pybossa/forms/forms.py
pybossa/forms/projects_view_forms.py
pybossa/forms/validator.py
pybossa/util.py
pybossa/view/projects.py
test/test_project_report.py

generate date range project report

---

pybossa/view/projects.py

*Issue number of the reported bug or feature request: #<2337>*
https://jira4.prod.bloomberg.com/browse/RDISCROWD-2337
check if value exists, if not, remove the key field

fix bpv bug

---

pybossa/repositories/task_repository.py

Update exported state

---

pybossa/exporter/export_helpers.py
pybossa/exporter/task_csv_export.py
pybossa/exporter/task_json_export.py

*Issue number of the reported bug or feature request: #<2589>*
https://jira4.prod.bloomberg.com/browse/RDISCROWD-2589
Add user_type column in postgresql statements and headers
Log the objects to test

Taskrun export

---

pybossa/exporter/task_csv_export.py

*Issue number of the reported bug or feature request: #<2499>*
https://jira4.prod.bloomberg.com/browse/RDISCROWD-2499
submodule

RDISCROWD-2499 add type attribute to text-input gcb

---

pybossa/view/projects.py
test/test_view/test_annotations.py

*Issue number of the reported bug or feature request: #<RDISCROWD-2687 & 2685>*
https://jira4.prod.bloomberg.com/browse/RDISCROWD-2687
https://jira4.prod.bloomberg.com/browse/RDISCROWD-2685
- (submodule) remove Label Aggregation Strategy dropdown from annotation setting page;
- (submodule) remove Input Schema input box  from annotation setting page; 
- (submodule) remove Output Schema input box  from annotation setting page; 
- corresponding backend change

UI change correspond to ampDisco schema change

---

pybossa/syncer/project_syncer.py

move bcos conn config to poller

---

pybossa/api/task_run.py
pybossa/syncer/__init__.py
test/test_api/test_api_announcement.py
test/test_api/test_api_blogpost.py
test/test_api/test_api_common.py
test/test_api/test_completedtask_api.py
test/test_syncer/__init__.py

do not use answer config from cache

---

pybossa/exporter/consensus_exporter.py
test/test_exporter/test_consensus.py

Export gold tasks on the consensus report.
Unit testing.

crowd-2764 export gold tasks for consensus report

---

pybossa/exporter/consensus_exporter.py
test/test_exporter/test_consensus.py

The consensus report should not include tasks with no answers.
Added unit test for the case.

crowd-2764 exclude gold tasks with no answers

---

pybossa/api/result.py

Allow update to calibration results

---

pybossa/view/projects.py

save answer locally

---

pybossa/api/__init__.py
test/test_api/test_project_api.py

Add guidelines_updated to user progress api

---

pybossa/importers/importer.py
test/test_view/test_user_import.py

if user exists, enable it

---

settings_test.py.tmpl

- Removed Chatlio.
Re: https://github.com/bloomberg/pybossa-default-theme/pull/254

Remove chatlio

---

pybossa/forms/forms.py
pybossa/jobs.py
pybossa/view/projects.py
test/test_jobs/test_progress_reminder.py
test/test_view/test_project_progress_reminder.py

*Issue number of the reported bug or feature request: #<2961>*
https://jira.prod.bloomberg.com/browse/RDISCROWD-2961

add webhook to task reminder

---

pybossa/view/projects.py

- Minor fix in text of contact email.

Contact email text fix

---

setup.py

- Removed webhook url from template.
Re: https://github.com/bloomberg/pybossa-default-theme/pull/267

RDISCROWD-2967 update theme for webhook remove

---

pybossa/forms/forms.py

*Issue number of the reported bug or feature request: RDISCROWD-2962*
Removed CKAN reference from forms.py
Checked a few projects to make sure change behaved as expected. Made minor changes and saved.
**Related PR**
https://github.com/bloomberg/pybossa-default-theme/pull/269

RDISCROWD-2962 Removed CKAN references

---

pybossa/cache/users.py
pybossa/data_access.py
pybossa/forms/dynamic_forms.py
pybossa/forms/fields/select_with_props.py
pybossa/forms/forms.py
pybossa/repositories/project_repository.py
pybossa/view/account.py
pybossa/view/projects.py
settings_test.py.tmpl
test/default.py
test/factories/project_factory.py
test/helper/web.py
test/test_admin.py
test/test_api/test_api_common.py
test/test_api/test_auditlog_api.py
test/test_api/test_newtask_passwd.py
test/test_api/test_project_api.py
test/test_api/test_project_by_name_api.py
test/test_api/test_update_gold_stats.py
test/test_auditlog.py
test/test_authorization/test_project_auth.py
test/test_autoimporter.py
test/test_coowners.py
test/test_data_access.py
test/test_json/test_project.py
test/test_locked_sched.py
test/test_repository/test_project_repository.py
test/test_view/test_project_clone.py
test/test_view/test_project_settings.py
test/test_web.py

input output data classification

---

pybossa/forms/forms.py

update data classification labels

---

pybossa/view/fileproxy.py
test/test_view/test_fileproxy.py

conditionally set response headers

---

pybossa/view/projects.py

1. Fix project-config call made by frontend to raise exception instead of silent error. Handle config KeyError resulting exception.
2. update wizard settings component to load as expected w/ public and priv instance.

project-config fix silent error

---

pybossa/cache/helpers.py
pybossa/cache/users.py
pybossa/data_access.py
pybossa/importers/importer.py
pybossa/repositories/task_repository.py
pybossa/sched.py
settings_local.py.tmpl
test/test_api/test_project_api.py
test/test_data_access.py
test/test_importers/__init__.py
test/test_locked_sched.py
test/test_user_pref_sched.py
test/test_view/test_project_clone.py
test/test_view/test_project_settings.py
test/test_web.py

RDISCROWD-3170: remove data access validation for tasks

---

pybossa/api/__init__.py

*Issue number of the reported bug or feature request: #<3011>*
https://jira.prod.bloomberg.com/browse/RDISCROWD-3011
Add more fields to `userprogress` api

RDISCROWD-3011 - add "completed_tasks, pending_tasks" to ampdb 'statistics table'

---

pybossa/view/bloomberg.py
test/test_view/test_bloomberg.py

I had to fix a test and the related logic for creating accounts from BSSO as in my mock I had BSSO returning false before creating a new user account. Because of this mistake users with successful BSSO returns were unable to create accounts (opposite of intended).
I revised the tests and also checked to see if the functionality was working as expected.

fix login error

---

test/test_web.py

https://jira.prod.bloomberg.com/browse/RDISCROWD-3216
Many tests were failing on merge after having passed on the branch. It seems that the rsa package was updated recently and that this update also had encoding implications.
I updated the rsa version and made the necessary adjustments to the tests.

RDISCROWD-3216: Fix failing tests

---

pybossa/view/bloomberg.py

https://jira.prod.bloomberg.com/browse/RDISCROWD-3215
Update with changes to theme.

RDISCROWD-3215: Update Theme

---

pybossa/forms/dynamic_forms.py

*Issue number of the reported bug or feature request: #<3237>*

RDISCROWD-3237 Make 'opt into AMP' checkbox stateful on page reload

---

package-lock.json
pybossa/api/project.py
pybossa/repositories/project_repository.py
pybossa/util.py
pybossa/view/projects.py
test/factories/project_factory.py
test/test_api/test_project_api.py
test/test_auditlog.py
test/test_coowners.py
test/test_repository/test_project_repository.py
test/test_web.py

*Issue number of the reported bug or feature request: Rdiscrowd 3250*
1. Updated API to match project creation page requirements
* Added ability to set password via api
* Moved `description_from_long_description` function to utils and added it to project api pre-processing
2. Updated project validation to require the same fields as project web form
3. Updated tests to fit new requirements

Rdiscrowd 3250 - Update project api to match UI

---

pybossa/util.py
test/test_util.py

- Added check for max int range for csv import of require_int fields.
```text
./run_tests test/test_util.py:TestPybossaUtil.test_is_int -s
Test is_int method. ... passed
-----------------------------------------------------------------------------
1 test run in 49.989 seconds (1 test passed)
```

RDISCROWD-3320 Max int validation for csv import require_int fields

---

pybossa/data_access.py
test/test_api/test_user_api.py
test/test_data_access.py
test/test_json/test_project.py
test/test_locked_sched.py
test/test_user_pref_sched.py
test/test_view/test_project_clone.py
test/test_view/test_project_settings.py
test/test_web.py

RDISCROWD 3302: Fix data access levels check

---

pybossa/exporter/consensus_exporter.py
pybossa/view/projects.py
test/test_exporter/test_consensus.py

*Issue number of the reported bug or feature request: #<3167>*
https://jira.prod.bloomberg.com/browse/RDISCROWD-3167
add function to parse answer field dot path and populate contributor's answer

RDISCROWD-3167: implement contributor's consensus answer for dot path

---

pybossa/repositories/project_repository.py

*Issue number of the reported bug or feature request: RDISCROWD-1714*
- Added new project fields to project export function
- Ran unit tests
- exported example csv: https://jira.prod.bloomberg.com/secure/attachment/356665/example_export.csv

RDISCROWD-1714: Update project report with new fields

---

pybossa/cache/task_browse_helpers.py

- Changed cache time from 1 week to 1 day for "Filter by Requests" field.

RDISCROWD-3400 Filter by requests field, updated cache period

---

pybossa/forms/validator.py

RDISCROWD-3470: handle empty pvf with optin checked

---

pybossa/cache/helpers.py
pybossa/jobs.py
pybossa/view/projects.py
test/test_cache/test_cache_helpers.py

*Issue number of the reported bug or feature request: RDISCROWD-3501*
Add a line in the UI which read a variable in the template. The variable gets the value from the DB. Also made two wording changes as requested.
All tests passed locally.
**Related PR**
https://github.com/bloomberg/pybossa-default-theme/pull/291

RDISCROWD-3501 Create Number of Priority 1 Tasks Info Field

---

pybossa/default_settings.py
pybossa/jobs.py
settings_local.py.tmpl
settings_test.py.tmpl
test/test_jobs/test_weekly_update.py

*Issue number of the reported bug or feature request: #<3544>*
https://jira.prod.bloomberg.com/browse/RDISCROWD-3544
Add unit test for new code;
Add logs for future debug after deployed

RDISCROWD-3544 add email report to admins 

---

pybossa/jobs.py

*Issue number of the reported bug or feature request: #<RDISCROWD-3593>*

RDISCROWD-3593 email report to admin

---

pybossa/default_settings.py
pybossa/jobs.py
test/test_jobs/test_weekly_update.py

*Issue number of the reported bug or feature request: #<RDISCROWD-3593>*
https://jira.prod.bloomberg.com/browse/RDISCROWD-3593

Fix email reports - fix bug, add tests, logs

---

pybossa/api/project.py
test/test_api/test_project_api.py
test/test_api/test_project_by_name_api.py

*Issue number of the reported bug or feature request: 3548*
Enable the publish API for project PUT method
Test locally
Related PRs:
- [amp dsp poller](https://bbgithub.dev.bloomberg.com/dtwebservices/amp-dsp-poller/pull/21)
- [gigw utils](https://bbgithub.dev.bloomberg.com/dtwebservices/gigw_utils/pull/67)

RDISCROWD-3548 Create linear execution paths for Workflows

---

test/test_api/test_project_api.py

fixing an issue on the [coveralls report](https://coveralls.io/builds/34721134/source?filename=pybossa/api/project.py#L63)

adding a test case to fix test coverage report

---

pybossa/exporter/consensus_exporter.py
test/test_exporter/test_consensus.py

https://jira.prod.bloomberg.com/browse/RDISCROWD-3727

RDISCROWD-3727 - fix user export error

---

pybossa/api/task_run.py
pybossa/view/fileproxy.py
test/test_api/test_taskrun_with_file.py
test/test_view/test_fileproxy.py

* encrypt task response under `private_json__encrypted_response` if task payload contains `private_json__encrypted_payload`

RDISCROWD-3797: Encrypt task response

---

pybossa/view/fileproxy.py
test/test_view/test_fileproxy.py

RDISCROWD-3797: Restrict task signature limit to 128

---

pybossa/exporter/consensus_exporter.py
test/test_exporter/test_consensus.py

*Issue number of the reported bug or feature request: #<3694>*
https://jira.prod.bloomberg.com/browse/RDISCROWD-3694

RDISCROWD-3694 show basic consensus when answer fields not configured

---

pybossa/view/bloomberg.py

*Issue number of the reported bug or feature request: #<3736>*
https://jira.prod.bloomberg.com/browse/RDISCROWD-3736

3736 move logs

---

README.md

RDISCROWD-2948 Updated readme.

---

pybossa/view/projects.py

added exception_type to logger for syncing when not an admin for production

---

README.md

RDISCROWD-2948 - Threshold default updated themes.

---

pybossa/model/user.py
pybossa/view/projects.py

- Added fix to show last submission task date for Last Activity on Delete Tasks and Delete Project pages.

RDISCROWD-1968 Last Activity showing zero

---

pybossa/view/projects.py
test/test_web.py

changed error message to be more specific for syncing error

changed error message to be more specific for syncing error

---

pybossa/model/user.py
pybossa/view/projects.py
test/test_syncer/test_project_syncer.py
test/test_web.py

Rdiscrowd 3933 add logger change errormsg

---

pybossa/view/projects.py
test/test_web.py

changed syncing error message

---

pybossa/api/task.py

Re: https://github.com/bloomberg/pybossa/pull/495

bugfix: update exported flag for regular/non-gold task

---

pybossa/api/__init__.py
test/test_api/test_project_api.py

RDISCROWD- 3842
added task progress method to filter tasks by task fields and task info fields
tested default functionality as well as task filter and task info filter

added task_progress method

---

pybossa/api/__init__.py

added cosmetic changes

---

test/test_web.py

update submodule pointer

---

pybossa/api/__init__.py
test/test_api/test_project_api.py

Rdiscrowd 4104: taskprogress api - add Null param value support

---

pybossa/api/task.py
pybossa/view/projects.py

Rdiscrowd 4114 - clearing memoized cache for pybossa.cache.task_browse_helpers.py

---

pybossa/api/__init__.py

Rdiscrowd 4104 emptystring support in URL

---

alembic/versions/17f20588b41e_add_worker_filter_to_task.py
alembic/versions/9483d60f9f4b_add_worker_pref_to_task.py
pybossa/importers/csv.py
pybossa/model/task.py
pybossa/sched.py
test/test_exporter/test_consensus.py
test/test_exporter/test_task_csv_exporter.py
test/test_sched_depth_first_all.py

*Issue number of the reported bug or feature request: #<4017>*
https://jira.prod.bloomberg.com/browse/RDISCROWD-4017
Update db schema, ORM, csv import functionality 
Manual

RDISCROWD-4017 add worker_pref, worker_filter db columns and task csv import 

---

pybossa/view/account.py

removed spaces before and after fullname

---

pybossa/exporter/consensus_exporter.py

resolved out of bounds index error

---

pybossa/data_access.py

removed amp_store default when creating a new project

---

pybossa/importers/csv.py
pybossa/model/task.py
pybossa/sched.py
test/test_exporter/test_consensus.py
test/test_exporter/test_task_csv_exporter.py
test/test_sched_depth_first_all.py

from pr 579 (require DB changes deployed)

---

pybossa/data_access.py
pybossa/syncer/project_syncer.py
test/test_syncer/test_project_syncer.py

Rdiscrowd 4246

---

pybossa/data_access.py

Revert "removed amp_store default when creating a new project"

---

pybossa/default_settings.py
pybossa/forms/validator.py
pybossa/repositories/project_repository.py

* Update to pvf name to contain 1-8 alpha characters

RDISCROWD-4473: Update PVF name format

---

test/test_web.py

- Updated themes with left-nav and checkbox fix.
Re: https://github.com/bloomberg/pybossa-default-theme/pull/309 https://github.com/bloomberg/pybossa-default-theme/pull/308

Updated themes.

---

pybossa/sched.py
settings_local.py.tmpl

*Issue number of the reported bug or feature request: #<4459>*
https://jira.prod.bloomberg.com/browse/RDISCROWD-4459

RDISCROWD-4459 - add task queue scheduler

---

pybossa/forms/forms.py
pybossa/view/projects.py
settings_local.py.tmpl
test/test_web.py

*Issue number of the reported bug or feature request: #< 4458 >*
https://jira.prod.bloomberg.com/browse/RDISCROWD-4458

RDISCROWD-4458 configurable columns for task queues

---

pybossa/cache/projects.py
pybossa/cache/task_browse_helpers.py

- Exclude displaying tasks that have been worked by current worker in the Task List for task queues.

RDISCROWD-4560 added sql to only show ongoing tasks if filter_user_prefs is true

---

pybossa/api/__init__.py
pybossa/cache/helpers.py
pybossa/jobs.py
pybossa/model/event_listeners.py
pybossa/sched.py
pybossa/view/projects.py
test/test_web.py

*Issue number of the reported bug or feature request: #<4416>*
https://jira.prod.bloomberg.com/browse/RDISCROWD-4416

RDISCROWD-4416 lock cherry pick tasks for user

---

pybossa/sched.py
pybossa/view/projects.py
test/test_api/test_project_api.py

- Added API endpoint to retrieve locked tasks for a project.
GET
**/project/my_project_name/locks**
```js
[
{
"admin": false, 
"email": "user1@test.com", 
"fullname": "User 1", 
"name": "user1", 
"seconds_remaining": 3596.96612405777, 
"subadmin": false, 
"task_id": 4, 
"user_id": "1"
}, 
{
"admin": true, 
"email": "user2@user.com", 
"fullname": "user2", 
"name": "user2", 
"seconds_remaining": 3598.8951799869537, 
"subadmin": false, 
"task_id": 2, 
"user_id": "2"
}
]
```
GET
**/project/my_project_name/locks/4**
```js
[
{
"admin": false, 
"email": "user1@test.com", 
"fullname": "User 1", 
"name": "user1", 
"seconds_remaining": 3596.96612405777, 
"subadmin": false, 
"task_id": 4, 
"user_id": "1"
}
]
```

RDISCROWD-4561 Locked tasks API

---

pybossa/sched.py

fix active users in cache

---

pybossa/cache/__init__.py
pybossa/cache/projects.py
pybossa/view/projects.py

https://jira.prod.bloomberg.com/browse/RDISCROWD-4386

RDISCROWD-4386 remove cache and add auto refresh for worker

---

pybossa/view/projects.py
test/test_web.py

*Issue number of the reported bug or feature request: #<4644>*
https://jira.prod.bloomberg.com/browse/RDISCROWD-4644

RDISCROWD-4644 manage access

---

pybossa/view/diagnostics.py

RDISCROWD-4648: hdfs health check

---

pybossa/view/diagnostics.py
pybossa/view/fileproxy.py

RDISCROWD-4648: healthcheck hdfs status

---

pybossa/view/projects.py

- Custom message for exporting by email
.

RDISCROWD-4678 Export email message

---

pybossa/api/__init__.py
pybossa/cache/helpers.py
pybossa/view/projects.py

included get_locked_tasks fix to both __init__.py and projects.py

---

pybossa/api/task.py

RDISCROWD-4674-lowercaseAPI

---

pybossa/redis_lock.py
pybossa/sched.py
test/test_reserve_task_category.py

RDISCROWD-4830: Python 3.9 fix reserve task category tests

---

pybossa/exporter/csv_reports_export.py
pybossa/importers/importer.py
pybossa/view/projects.py
test/test_project_report.py

fix project report export in QA

---

pybossa/view/projects.py
test/test_view/test_assign_task_worker.py

update themes pointer

---

pybossa/redis_lock.py
test/test_api/test_project_api.py

*Issue number of the reported bug or feature request: #<4841>*

RDISCROWD-4841 release expired bundling before read/write

---

pybossa/cache/projects.py
pybossa/sched.py
pybossa/view/projects.py

*Issue number of the reported bug or feature request: #<4704>*

RDISCROWD-4704 show task based on task bundling

---

pybossa/cache/task_browse_helpers.py

check for list typein batch assignment

---

pybossa/cache/task_browse_helpers.py

front end ticket: https://github.com/bloomberg/pybossa-default-theme/pull/339

RDISCROWD-4597 Enable Ability to Sort Customized Columns in the Task List

---

pybossa/exporter/task_csv_export.py
pybossa/jobs.py
pybossa/util.py
test/test_jobs/test_export.py
test/test_jobs/test_maintenance.py
test/test_util.py

*Issue number of the reported bug or feature request: Rdiscrowd 4885*
- Deprecate UnicodeWriter class which causes disk space full. Instead, using Pandas to handle csv
Performed in [QA](https://qa.gigwork.net/project/transcribe/tasks/).

Rdiscrowd 4885 Large Export Files Not Downloading

---

pybossa/cache/projects.py

*Issue number of the reported bug or feature request: #<RDISCROWD-4832>*

RDISCROWD-4832 update sql

---

pybossa/cache/project_stats.py
test/test_repository/test_projectstats_repository.py

*Issue number of the reported bug or feature request: #<RDISCROWD-4832>*

RDISCROWD-4832 clean session

---

pybossa/jobs.py

*Issue number of the reported bug or feature request: #Rdiscrowd 4900*
Add request_context() in the functions of jobs.py so that it has "request" object available. This is to avoid the error "RuntimeError: Working outside of request context."
Tested in QA

Rdiscrowd 4900 cache warmup issue showing in the RQ

---

pybossa/cache/projects.py
pybossa/jobs.py
test/test_jobs/test_project_stats.py

build project stats for recently updated projects

---

pybossa/cache/projects.py
pybossa/cache/task_browse_helpers.py

SQL optimization to reduce processing time of the task browse page from 8000 ms to ~15ms.

RDISCROWD-4913 Optimize task browse SQL

---

pybossa/cache/projects.py

*Issue number of the reported bug or feature request: #<4913>*

RDISCROWD-4913 Optimize Task Browse SQL - fix sorting by complete

---

pybossa/cloud_store_api/s3.py

RDISCROWD-4946: Remove fileproxy decode

---

pybossa/encryption.py

RDISCROWD-4946: handle decryption decode

---

pybossa/cache/projects.py

*Issue number of the reported bug or feature request: RDISCROWD-4904*
Select top 20 first, then from the top 20, select the top1, so that SQL optimizer works better
Local
running time 7.8s -> 10ms

RDISCROWD-4904 Fix Gigwork cache miss - step 1: optimize SQL

---

pybossa/cache/projects.py

RDISCROWD-4913 Optimize task browse 2

---

pybossa/jobs.py
pybossa/repositories/user_repository.py
pybossa/util.py
test/test_repository/test_user_repository.py
test/test_util.py

RDISCROWD-4976: Optimize sql queries for email recipient, bcc list

---

pybossa/view/projects.py

RDISCROWD-4925 Tasklist default page size 30

---

pybossa/cache/task_browse_helpers.py
pybossa/view/projects.py

*Issue number of the reported bug or feature request: #<4965>*

RDISCROWD-4965 Fix sorting on customized columns 

---

pybossa/cache/task_browse_helpers.py
pybossa/view/projects.py

Revert "RDISCROWD-4965 Fix sorting on customized columns "

---

pybossa/cache/projects.py
test/test_cache/test_cache_projects.py

RDISCROWD-4982 improve sorting by active users

---

accessdb.py
alembic/versions/82cb40487506_archived_tables.py
create_bulk_tasks.py
purge_data.py

RDISCROWD-4953: Archive and purge data

---

alembic/versions/c7d7de1f09f6_rdiscrowd_4957_admin_dashbaord_add_task_.py
app_context_rqworker.py
pybossa/cache/__init__.py
pybossa/cache/projects.py
pybossa/cache/site_stats.py
pybossa/jobs.py
pybossa/view/admin.py
test/test_cache/__init__.py
test/test_cache/test_site_stats.py

*Issue number of the reported bug or feature request: RDISCROWD-4957*
Made a bunch of optimizations to ensure the job for calculating the statistics of admin dashboard can finish in the desired time.
Tested locally
Tested in QA https://qa.gigwork.net/admin/management_dashboard/ and it is working.

RDISCROWD-4957 Optimize Admin Management Dashboard

---

alembic/versions/82cb40487506_archived_tables.py

update archive tables

---

purge_data.py

purge data by proj id, handle bool, parameterized sql

---

pybossa/view/fileproxy.py
test/test_view/test_fileproxy.py

RDISCROWD-4910 add endpoint for workflow_url

---

pybossa/cache/task_browse_helpers.py
test/test_cache/test_cache_helpers.py

- Bug fix for column sorting when a column name contains a substring of the column to be sorted.

RDISCROWD-5118 Bug fix for column sorting substring.

---

pybossa/cache/projects.py

*Issue number of the reported bug or feature request: #<RDISCROWD-5070>*

RDISCROWD-5070 - fix reference bug

---

pybossa/view/projects.py
test/test_web.py

Avoid sorting of task list columns before passing it to the task scheduler html page.

RDISCROWD-5073: Avoid sorting of task list cols

---

pybossa/forms/forms.py
pybossa/view/projects.py
test/test_web.py

RDISCROWD-4703: Add reserve category column to UI

---

pybossa/api/__init__.py
test/test_web.py

- Fix for lock timestamp to be static (original lock timestamp), rather than changing per refresh.

RDISCROWD-5040 Lock timestamp fix

---

pybossa/view/projects.py

- Bug fix for customized columns lost on saving from wizard.
Re: https://github.com/bloomberg/pybossa-default-theme/pull/369

RDISCROWD-5267 Update themes

---

pybossa/auth/task.py
pybossa/util.py
pybossa/view/projects.py
test/test_authorization/test_task_auth.py
test/test_util.py

RDISCROWD-5242: Enable task updates for regular coowner

---

pybossa/util.py
pybossa/view/projects.py
test/test_util.py

*Issue number of the reported bug or feature request: [RDISCROWD-5174]*
Using BeautifulSoup to manipulate TP code and incorporate response
Test locally

Rdiscrowd 5174 display response for tp components

---

pybossa/api/bulktasks.py
pybossa/core.py
pybossa/settings_local.py.tmpl

RDISCROWD-5321: rate limit for bulk apis

---

pybossa/util.py
pybossa/view/projects.py
test/test_util.py

*Issue number of the reported bug or feature request: RDISCROWD-5249*
Using BeautifulSoup to parse the TP code:
- Grab the user response and use it to set the "data" attribute
- Remove initial-value attribute so that table can display the data
Testing is performed locally

RDISCROWD-5249 Display Completed Responses for Table TP Component

---

pybossa/view/projects.py

- Added audit log for add_coowner and del_coowner API methods.

RDISCROWD-5091 Audit log for coowner updates

---

pybossa/sched.py
test/test_reserve_task_category.py

RDISCROWD-5385: Gracefully handle reserve task category for private instance

---

pybossa/view/projects.py

- Added ability to add/remove email contacts for a project.
```
127.0.0.1 - - [17/Aug/2022 12:08:05] "POST /project/hello/coowners HTTP/1.1" 200 -
pybossa:INFO:[2022-08-17 12:08:56,950] Contact email sent from user id 1 (user) to recipients ['user@user.com', 'worker1@worker.com'] for project id 1 (hello, hello) [in /mnt/c/Projects/gigwork/pybossa/pybossa/view/projects.py:3993]
```
```
127.0.0.1 - - [17/Aug/2022 12:10:21] "POST /project/hello/coowners HTTP/1.1" 200 -
pybossa:INFO:[2022-08-17 12:10:25,649] Contact email sent from user id 1 (user) to recipients ['user@user.com'] for project id 1 (hello, hello) [in /mnt/c/Projects/gigwork/pybossa/pybossa/view/projects.py:3993]
```
Re: https://github.com/bloomberg/pybossa-default-theme/pull/373

RDISCROWD-4848 - Custom email contacts

---

pybossa/util.py
pybossa/view/projects.py
test/test_util.py

*Issue number of the reported bug or feature request: RDISCROWD-5305*
- Add support for input-text-area for displaying completed responses.
- Automatically add the proper 'initial-value' programmatically
- Append the task.info (questions) to the answer payload so that they too will show in the preview mode
Tested perform locally.

RDISCROWD-5305 Display Completed Responses in the Task View - TextArea Box

---

pybossa/view/projects.py

RDISCROWD-5371: task browse: show all answers for gold tasks

---

pybossa/cache/helpers.py

RDISCROWD-5373: memoize n_available_tasks_for_user

---

pybossa/cache/helpers.py

log proj id, user id

---

.github/workflows/github-actions.yml
test/test_api/test_task_api.py

*Issue number of the reported bug or feature request: RDISCROWD-5386*
- Update Redis to 6.2.7 in Github Actions
- Update Postgresq to 13.6 in Github Actions
Tested locally

RDISCROWD-5386-update-redis-6.2

---

pybossa/view/projects.py

- Bug fix for coowners empty request.data.
Re: https://github.com/bloomberg/pybossa/pull/776

RDISCROWD-5412-2 Bug fix for coowners page empty request.data.

---

pybossa/view/projects.py

Issue number of the reported bug or feature request: RDISCROWD-5432
Add a dropdown UI for configuring auto deleted completed tasks days.
local
related PR: https://github.com/bloomberg/pybossa-default-theme/pull/378

RDISCROWD-5432 Auto delete completed tasks after n days: UI changes

---

pybossa/view/admin.py

RDISCROWD-5482: Log enable/disable user activity

---

.github/workflows/github-actions.yml
accessdb.py
create_bulk_tasks.py
pybossa/core.py
pybossa/jobs.py
pybossa/view/admin.py
settings_test.py.tmpl
test/test_admin.py
test/test_jobs/__init__.py

RDISCROWD-5431: Performing completed tasks cleanup via admin/cleanuptasks

---

pybossa/cache/helpers.py

RDISCROWD-5545: limit available tasks magic number

---

pybossa/cache/projects.py

- Fixed bug with priority being overwritten with user name while sorting on "completed by" column.

RDISCROWD-5531 Fixed missing comma in completed by sql

---

pybossa/cache/projects.py
test/test_web.py

- Disable sort.
- Update themes.

RDISCROWD-5531 Disable sort. Update themes.

---

pybossa/forms/forms.py
pybossa/view/projects.py

RDISCROWD-5626: Handle edit task submission config

---

pybossa/api/__init__.py
test/test_web.py

*Issue number of the reported bug or feature request: RDISCROWD-5629*
- Added a new API to assign a task to a user
- Updated pybossa-default-theme pointer
Tested locally
Related PRs:
- https://github.com/bloomberg/pybossa.js/pull/19
- https://github.com/bloomberg/pybossa-default-theme/pull/392

RDISCROWD-5629 add allow-assign-to-user to assign task

---

pybossa/api/__init__.py
test/test_web.py

*Issue number of the reported bug or feature request: RDISCROWD-5684*
Update assign API to support un-assign user from the task
Tested lcoally
Related PRs:
https://github.com/bloomberg/pybossa.js/pull/20
https://github.com/bloomberg/pybossa-default-theme/pull/396

RDISCROWD-5684 update to auto save and assign

---

pybossa/settings_local.py.tmpl
settings_test.py.tmpl

Re: https://github.com/bloomberg/pybossa-default-theme/pull/389

RDISCROWD-5652 Added logo color config for dev.

---

pybossa/api/__init__.py

*Issue number of the reported bug or feature request: RDISCROWD-5717*
Added a safe check and updated the pybossa-theme-default pointer
Tested locally
Related PRs:
https://github.com/bloomberg/pybossa.js/pull/23
https://github.com/bloomberg/pybossa-default-theme/pull/402

RDISCROWD-5717 change banner position for save and assign

---

pybossa/model/event_listeners.py

RDISCROWD-5627: reset exported upon taskrun edit

---

pybossa/view/projects.py

RDISCROWD-5703: Allow edit submission for admins, subadmins

---

pybossa/view/projects.py

RDISCROWD-5784: Filters with edit submissions

---

pybossa/view/account.py

*Issue number of the reported bug or feature request: [RDISCROWD-5743](https://jira.prod.bloomberg.com/browse/RDISCROWD-5743)*
Add CSRF ignore decorator to prevent missing CSRF token errors.
Main PR: 
- https://github.com/bloomberg/pybossa/pull/832

RDISCROWD-5743 task browse bookmarks (add CSRF ignore)

---

pybossa/view/account.py
pybossa/view/projects.py
test/test_web.py

Rdiscrowd 5742 taskbrowse bookmarks UI 2

---

pybossa/api/__init__.py
pybossa/repositories/project_repository.py
test/test_web.py

Endpoint
`/api/project/<short_name>/gold_annotations`

RDISCROWD-6413: Add gold_annotations api

---

pybossa/api/__init__.py
pybossa/api/api_base.py
pybossa/api/docs/project/project_delete.yaml
pybossa/api/docs/project/project_get.yaml
pybossa/api/docs/project/project_post.yaml
pybossa/api/docs/project/project_put.yaml
pybossa/api/docs/task/task_delete.yaml
pybossa/api/docs/task/task_get.yaml
pybossa/api/docs/task/task_post.yaml
pybossa/core.py
setup.py
test/test_hateoas.py

*Issue number of the reported bug or feature request: [RDISCROWD-6484](https://jira.prod.bloomberg.com/browse/RDISCROWD-6484)*
- Add Swagger UI to pybossa using `flasgger`
- Adds documentation for `/api/task` and `/api/project`
- Documentation visible at {gigwork_url}/apidocs/#/ (example: http://localhost:5000/apidocs/#/)
Tested locally

RDISCROWD-6484 Swagger UI base implementation

---

pybossa/api/task_run.py
pybossa/cloud_store_api/s3.py
pybossa/task_creator_helper.py
setup.py

* Record priv response under v2 staging buckets.
* Add botocore dependency for boto3

RDISCROWD-6676: Record priv response under v2 staging buckets.

---

pybossa/api/__init__.py

*Issue number of the reported bug or feature request: [RDISCROWD-6709](https://jira.prod.bloomberg.com/browse/RDISCROWD-6709)*
remove proxies from llm calls

RDISCROWD-6709 remove proxies from llm calls

---

pybossa/syncer/project_syncer.py
test/test_syncer/test_project_syncer.py

*Issue number of the reported bug or feature request: RDISCROWD-6710*
Do not sync *project_users* between projects.
Unit tests.

RDISCROWD-6710 - Do not sync project_users

---

pybossa/task_creator_helper.py

RDISCROWD-6675: BCOS v2: Gold task conn based on store type under url path

---

pybossa/core.py
pybossa/settings_local.py.tmpl

*Issue number of the reported bug or feature request: RDISCROWD-6680*
move swagger header file path to config
Tested locally

RDISCROWD-6680 move swagger header path to config

---

pybossa/api/__init__.py
test/test_api/__init__.py

*Issue number of the reported bug or feature request: [RDISCROWD-6763](https://jira.prod.bloomberg.com/browse/RDISCROWD-6763)*
- migrate to using Autolab LLM inference API due to change in authorization method in LLM team's endpoint
Tested locally

RDISCROWD-6763 Autolab LLM Inference API

---

pybossa/api/task.py
pybossa/core.py
pybossa/view/fileproxy.py
test/test_api/test_task_api.py
test/test_view/test_fileproxy.py

RDISCROWD-6853: Deprecate hdfs

---

pybossa/redis_lock.py
test/test_cache/test_cache_projects.py

- Release lock for deleted task.

RDISCROWD-7224 Clear cache for deleted task

---

pybossa/api/__init__.py

*Issue number of the reported bug or feature request: RDISCROWD-7185*
Add an access token
Tested locally
None

RDISCROWD-7185 Update LLM analysis engine (Autolab) static token

---

.coveragerc
.github/workflows/github-actions.yml
pybossa/api/__init__.py
test/test_api/__init__.py

*Issue number of the reported bug or feature request: RDISCROWD-7292*
Include the user id when calling inference_endpoint
None

RDISCROWD-7292 Update GIGwork AutoLab LLM with User ID

---

test/test_view/test_project_answer_field_config.py
test/test_view/test_project_summary.py

*Issue number of the reported bug or feature request: RDISCROWD-6334*
update themes pointer
https://github.com/bloomberg/pybossa-default-theme/pull/454

RDISCROWD-6334 update themes

---

pybossa/syncer/__init__.py
pybossa/syncer/project_syncer.py
pybossa/view/projects.py

- add proxy when syncing project between environments

add project sync proxies

---

pybossa/view/projects.py

*Issue number of the reported bug or feature request: DRQS 175518371*
add csrf exempt to `/locks` to allow REST API access
Tested locally

add csrf exempt to locks

---

pybossa/api/__init__.py

RDISCROWD-7195: Under gold mode, disable lock task state for proj owners

---

pybossa/jobs.py
pybossa/repositories/task_repository.py
pybossa/settings_local.py.tmpl
test/test_jobs/test_delete_tasks.py

RDISCROWD-7379: Delete tasks based on session_replication role

---

pybossa/api/__init__.py
test/test_api/__init__.py

*Issue number of the reported bug or feature request: RDISCROWD-7366*
Updated default model to be mixtral.
Tested locally with sample project.
Related settings files have already been updated.

RDISCROWD-7366: add mixtral as default

---

pybossa/api/__init__.py

*Issue number of the reported bug or feature request*: [RDISCROWD-7459](https://jira.prod.bloomberg.com/browse/RDISCROWD-7459)
Removed token from body and added to headers
Tested locally with a sample project.

RDISCROWD-7459: add token to header

---

pybossa/api/__init__.py
settings_test.py.tmpl
test/test_api/__init__.py

[RDISCROWD-7467](https://jira.prod.bloomberg.com/browse/RDISCROWD-7467): Update request and model params for new Autolab request to OpenAI endpoint.
- updated documentation to reflect new payload structure
- updated AUTOLAB request to use model name instead of endpoint
- moved data extraction from request into separate module
- updated response processing to reflect new structure
- updated tests to reflect the new request and response structures

RDISCROWD-7467: Autolab update

---

pybossa/forms/forms.py
pybossa/repositories/project_repository.py
pybossa/view/projects.py
test/test_json/test_project.py
test/test_repository/test_project_repository.py

*Issue number of the reported bug or feature request: [RDISCROWD-7338](https://jira.prod.bloomberg.com/browse/RDISCROWD-7338)
- make project password optional instead of required

RDISCROWD-7338 Project password optional

---

pybossa/api/api_base.py
pybossa/cache/task_browse_helpers.py
pybossa/repositories/__init__.py
test/test_cache/test_cache_projects.py

- Added ability to filter by assigned user in the browse tasks.
Re: https://github.com/bloomberg/pybossa-default-theme/pull/461

RDISCROWD-7286 Filter by assign user

---

pybossa/view/account.py
pybossa/view/projects.py

*Issue number of the reported bug or feature request: [RDISCROWD-7532](https://jira.prod.bloomberg.com/browse/RDISCROWD-7532)*
- backend changes to support building grafana dashboard link on frontend
tested locally.
**Additional Info**
https://github.com/bloomberg/pybossa-default-theme/pull/462

RDISCROWD-7532 Grafana Dashboard Link

---

pybossa/cache/projects.py
pybossa/cache/task_browse_helpers.py
test/test_cache/test_cache_projects.py

- Added tooltip for Email to assigned users filter.
- Sorted list of assigned user names and emails.
Re: https://github.com/bloomberg/pybossa-default-theme/pull/463

RDISCROWD-7286 Assign user filter tooltip

---

pybossa/auth/project.py
test/test_web.py

*Issue number of the reported bug or feature request: RDISCROWD-7338*
- Make project access forbidden to users when on public gigwork with no password set and no users assigned to project

RDISCROWD-7338 update

---

pybossa/service_validators.py
test/test_service_validators.py

*Issue number of the reported bug or feature request: [RDISCROWD-7595](https://jira.prod.bloomberg.com/browse/RDISCROWD-7595)*
allow forward slash in service validators
tested locally

RDISCROWD-7595 allow forward slash in service validators

---

pybossa/util.py

*Issue number of the reported bug or feature request: [RDISCROWD-7336](https://jira.prod.bloomberg.com/browse/RDISCROWD-7336)*
Add `text-tagging` to `TP_COMPONENT_TAGS`

add text-tagging

---

pybossa/view/projects.py

* update themes
* project-config endpoint to load/save reset_presented_time upon get/save called from UI

RDISCROWD-7602: Reset presented time UI changes

---

pybossa/view/projects.py

Testing performed
* reset_presented_time can be set and unset via settings wizard
* updating ext_config via project settings and wizard works

RDISCROWD-7602: add check for ext_config before updating project settings

---

pybossa/cache/users.py
pybossa/view/projects.py
test/test_web.py

- Added feature to sort users by last name.
- Added tooltip with email address.
- Hide disabled users.
Re: https://github.com/bloomberg/pybossa-default-theme/pull/466

RDISCROWD-7561 Assign Users UI Enhancements

---

pybossa/cache/users.py
pybossa/view/projects.py
test/test_web.py

- Ignore last names with digits.

RDISCROWD-7561 Assign users project last name

---

pybossa/cache/users.py
pybossa/util.py
pybossa/view/projects.py
test/test_util.py
test/test_web.py

- Strip whitespace from front/end of last names.
- Refactor.
_Fixes issue when a fullname ends in whitespace, previously resulting in the last_name being `' '` and sorting to the top._

RDISCROWD-7561 Enhance assign user UI

---

pybossa/jobs.py

- Removed EXTENDED_STALE_USERS_MONTHS unused variable.

RDISCROWD-6328 Removed unused config variable.

---

pybossa/repositories/task_repository.py

Revert delete_zip from task_repo.delete

---

pybossa/repositories/task_repository.py

delete task profiling: use time.perf_counter instead of time.time

---

pybossa/repositories/task_repository.py
test/test_api/test_task_api.py
test/test_repository/test_task_repository.py

delete task api. direct sql. remove delete_zip

---

pybossa/api/__init__.py
pybossa/api/project.py
pybossa/view/projects.py
test/test_view/test_project_ext_config.py
test/test_view/test_project_summary.py
test/test_web.py

*Issue number of the reported bug or feature request: #RDISCROWD-7660*
support authorized service list

RDISCROWD-7660 - support authorized service list

---

pybossa/model/event_listeners.py
pybossa/repositories/task_repository.py

RDISCROWD-7766: skip delete task from counter

---

pybossa/cache/site_stats.py
pybossa/view/admin.py
test/test_cache/test_site_stats.py

- Added `Last Submission Date` and `Published` to the usage dashboard.
- Sort list of projects using each component by Last Submission date descending.
Re: https://github.com/bloomberg/pybossa-default-theme/pull/475

RDISCROWD-7794 Component Usage Dashboard updates

---

pybossa/view/projects.py

*Issue number of the reported bug or feature request: #RDISCROWD-7660*

RDISCROWD-7660-2 show authorized services to non-admins

---

pybossa/view/projects.py

*Issue number of the reported bug or feature request: #RDISCROWD-7660*

Remove authorized services form from ext-config page

---

pybossa/util.py

- Increased max size for csv.reader().

Increased max size for csv.reader().

---

pybossa/api/__init__.py
settings_test.py.tmpl
test/test_api/__init__.py
test/test_util.py

*Issue number of the reported bug or feature request: #RDISCROWD-7778*

RDISCROWD-7778 - update LLM

---

pybossa/util.py
test/test_util.py
test/test_web.py

*Issue number of the reported bug or feature request: [RDISCROWD-7362](https://jira.prod.bloomberg.com/browse/RDISCROWD-7362)*
- sort country codes and country name lists
- Group country names with their country codes in the combined `locations` list

RDISCROWD-7362 Sort Country Codes and Country Names

---

pybossa/jobs.py
test/test_jobs/test_delete_tasks.py

RDISCROWD-7864: Update delete in batches

---

pybossa/api/__init__.py
pybossa/settings_local.py.tmpl
test/test_web.py

*Issue number of the reported bug or feature request: #RDISCROWD-7850*

RDISCROWD-7850 - update 403 error for authorized services

---

pybossa/api/docs/project/project_clone.yaml
pybossa/view/projects.py
test/test_api/test_project_api.py

*Issue number of the reported bug or feature request: [RDISCROWD-7842](https://jira.prod.bloomberg.com/browse/RDISCROWD-7842)*
add an optional copy coowners flag to project clone API
Tested locally
https://github.com/bloomberg/pybossa/pull/1017

RDISCROWD-7842 add copy coowners flag to project clone API

---

pybossa/api/project.py
pybossa/api/task.py
pybossa/importers/importer.py
pybossa/repositories/task_repository.py
pybossa/task_creator_helper.py
test/test_api/test_task_api.py
test/test_web.py

RDISCROWD-7705: Perform duplicate check using checksum

---

pybossa/repositories/project_repository.py
pybossa/view/projects.py
test/test_repository/test_project_repository.py

*Issue number of the reported bug or feature request: RDISCROWD-7917*

RDISCROWD-7917 - add project.info character validation

---

pybossa/view/projects.py
test/test_view/test_project_ext_config.py

*Issue number of the reported bug or feature request: RDISCROWD-7917*

RDISCROWD-7917 - Flash error banner on ext-config page

---

pybossa/view/projects.py

*Issue number of the reported bug or feature request: [RDISCROWD-6093](https://jira.prod.bloomberg.com/browse/RDISCROWD-6093)*
edit error message upon going to the task presenter before actually importing any tasks in a draft project
Tested locally

RDISCROWD-6093 edit error msg

---

pybossa/importers/importer.py
test/test_importers/test_importer_validation.py

RDISCROWD-7707: Validate genid fields under import csv

---

pybossa/api/task.py
pybossa/importers/importer.py
pybossa/task_creator_helper.py
test/test_web.py

RDISCROWD-7941: generate checksum. unified method to obtain project info by id

---

.github/workflows/github-actions.yml
pybossa/forms/fields/select_two.py
pybossa/forms/forms.py
pybossa/view/projects.py
test/test_view/test_project_settings.py

*Issue number of the reported bug or feature request: RDISCROWD-7779*

RDISCROWD-7779 - add duplicate field settings

---

.github/workflows/github-actions.yml

Post-coveralls outage, re-enable coverage reports.

Re-enable code coverage

---

pybossa/task_creator_helper.py

RDISCROWD-7780: duplicate task check file path

---

pybossa/view/projects.py
test/test_api/test_project_api.py

*Issue number of the reported bug or feature request: #RDISCROWD-7987*
The cloned project should not have the same created or updated date as the original project.

RDISCROWD-7987 do not clone the created & updated attrs

---

pybossa/task_creator_helper.py

RDISCROWD-7866: Obtain priv data for dupcheck only when duplicate check is configured

---

pybossa/task_creator_helper.py

dupcheck fix typo

---

pybossa/api/task.py
pybossa/task_creator_helper.py

fix logging format error

---

pybossa/core.py
pybossa/jobs.py
pybossa/sentinel/__init__.py
pybossa/view/account.py
test/test_emailsvc.py

RDISCROWD-8242: Private sync 3. Update redis config for rq. Normalize email aliases for email service

---

pybossa/api/__init__.py
pybossa/cache/task_browse_helpers.py
test/test_cache/test_cache_helpers.py
test/test_jobs/test_export_tasks.py

RDISCROWD-8129: Worker filter value to cast to float when needed
