pybossa/exporter/__init__.py, pybossa/exporter/csv_reports_export.py, pybossa/exporter/project_csv_export.py, pybossa/jobs.py, test/test_project_report.py
There is no need to for the project report to be uploaded before it is sent to the client.  Instead, we can simply send the file in the response.
=> CROWD-1236 remove project export urls

pybossa/repositories/task_repository.py, test/test_repository/test_task_repository.py
Update only the corresponding state during redundancy updates. This is related to the bug that Andrew reported last week.
=> Update only the corresponding states during redundancy updates

pybossa/importers/csv.py, pybossa/model/event_listeners.py, test/test_model/test_event_listeners.py
Fix bug when adding gold task from CSV and not update the state if project is not published
=> Fix bug RDISCROWD-1403

pybossa/forms/account_view_forms.py, pybossa/forms/forms.py, pybossa/view/account.py, test/test_web.py
Provide a page where users can input the password reset key rather than require them to follow a URL.
=> Reset password alternate route

pybossa/api/__init__.py
- Only project owners, sub-admin co-owners, and administrators may update a Gold task for a project.
*Note: To create a project, a user must be either an admin or sub-admin. The project owner and co-owners will be included in `project.owners_ids`. If a co-owner is not a sub-admin, they will only have read access to gold tasks.*
Referencing https://github.com/bloomberg/pybossa-default-theme/pull/122
=> RDISCROWD-1635: Disable updating a Gold task for non-owners of a project

run_tests, test/default.py
- Updated delete indexes in the test setup to check against the current schema. This resolves an issue with trying to delete indexes found in other schemas that do not exist in the current one.
- Updated the `./run_tests` shortcut for cross-compatibility.
=> Fix for database unit test setup

test/test_jobs/test_schedule_jobs.py
- Replace hard-coded `mymaster` with `settings_test.REDIS_MASTER_NAME` from settings_test.py
When running the tests locally, this change allows the tests in `test_schedule_jobs.py` to pass, as my REDIS is not named `mymaster`.
Does it make sense to include this change?
=> Replace hard-coded test using "mymaster" with settings_test.py config

pybossa/otp.py, pybossa/view/account.py, test/test_otp.py
- Added config option to bypass two-factor authentication based upon login email address.
- Support for automated testing specific login email address.
```python
ENABLE_TWO_FACTOR_AUTH = True
BYPASS_TWO_FACTOR_AUTH = ['user1@user.com', 'user2@user.com']
```
=> RDISCROWD-1500 Bypass two-factor authentication via config list

pybossa/forms/forms.py, pybossa/model/user.py, pybossa/view/projects.py, test/test_web.py
*Issue number of the reported bug or feature request: #RDISCROWD-1815*
Added a new setting, completion mode, to quiz mode configuration. It lets the project owner configure whether the quiz will present all the questions regardless of how the worker answers, or if it will end the quiz as soon as the pass/fail status is known.
Manual testing
=> Add quiz completion mode setting.

pybossa/view/projects.py
RDISCROWD-1971
When managing co-owners, two of the wizard icons are differently colored
=> Pass project_sanitize object since it contains all data used by the wizard to load properly

pybossa/importers/csv.py, test/test_importers/test_localCSV_importer.py
*Issue number of the reported bug or feature request: #RDISCROWD_2043*
In CSV task import, we used to require a field to end with _priv_gold to store it as a private gold answer. We would remove that suffix to get the actual field name. We changed the behavior to store all gold answers on private GIGwork as private, so we stopped looking for _priv_gold and just
looked for _gold. That meant that a field imported with _priv_gold suffix will just have _gold removed and _priv will still be at the end of the name, which will leave us storing the wrong name.
This PR removes the _priv_gold suffix in addition to the _gold suffix.
New unit tests
=> Handle _priv_gold fields in CSV task import.

pybossa/api/task.py, pybossa/cache/helpers.py, pybossa/importers/importer.py, pybossa/sched.py, pybossa/task_creator_helper.py, test/test_importers/__init__.py
*Issue number of the reported bug or feature request: #RDISCROWD-1878*
Adding a new task state, "enrich", for tasks that are imported by CSV when there are enrichment settings configured on a project. These tasks will not be scheduled to workers while in the "enrich" state. The task poller will pull these tasks into BBDS and then they will be enriched by the BBDS listener and then pushed back to gigwork with enriched request fields and a state of "ongoing".
Manual and unit tests.
=> Support enrichment for CSV imported tasks.

pybossa/importers/csv.py
*Issue number of the reported bug or feature request: #RDISCROWD-1878*
In CSV task import, if a column for a reserved task property (other than user_pref) is blank then don't initialize that property on the task. Current code initializes the property to empty string.
Reserved properties are:
state
quorum
calibration
priority_0
n_answers
expiration
Manual and unit test.
=> Don't initialize blank task properties in csv import.

pybossa/sched.py, test/test_web.py
When the task scheduler is user pref, we only create golds for tasks that that match the user's preferences
=> Gold no user assign

pybossa/forms/forms.py, pybossa/importers/base.py, pybossa/importers/csv.py, pybossa/importers/dropbox.py, pybossa/importers/epicollect.py, pybossa/importers/flickr.py, pybossa/importers/iiif.py, pybossa/importers/importer.py, pybossa/importers/s3.py, pybossa/importers/twitterapi.py, pybossa/importers/youtubeapi.py, pybossa/jobs.py, pybossa/model/project.py, pybossa/view/projects.py, test/test_auditlog.py, test/test_autoimporter.py, test/test_importers/__init__.py, test/test_importers/test_csv_importer.py, test/test_importers/test_googledocs_importer.py, test/test_importers/test_importer_validation.py, test/test_importers/test_localCSV_importer.py, test/test_web.py
*Issue number of the reported bug or feature request: #RDISCROWD-2140*
We want to be able to turn off the validation of CSV import headers against the fields used in task presenter. We also need to do more validation of headers related to enrichment. For tasks to be enriched, the enrichment output field can not have a value in the import. Also validating the task state to be either "enrich" or "ongoing" or missing. Also, for empty cells we are ignoring the value instead of importing an empty string.
We are also fixing the bug where validation of import fields against the fields used in the task presenter code was not comparing the actual field name when the header field contained a suffix. We now strip off the suffix before comparing.
Manual …
=> Validate CSV headers.

pybossa/api/project.py, pybossa/data_access.py, pybossa/forms/dynamic_forms.py, test/test_view/test_project_settings.py
Opt in amp storage by default from ui and through api 
create new project, opt-in amp store option checked. updated existing project and confirmed from ui and api, opt-in config set as expected. created project via api, opt-in was set.
=> amp opt-in default checked

pybossa/view/projects.py, test/test_web.py
When updating the completion mode and clicking reset for a user the users settings where not getting updated as expected. The code was depending on the data from the user itself instead of the data configured by the project. Removed 2 lines and add test to cover that case.
=> Completion mode wasnt updating to the new settings

pybossa/api/__init__.py, pybossa/cache/helpers.py, pybossa/cache/projects.py, pybossa/view/projects.py, test/test_cache/test_cache_helpers.py
*Issue number of the reported bug or feature request: #<2441>*
https://jira4.prod.bloomberg.com/browse/RDISCROWD-2441
- exclude gold tasks when computing `total number of tasks remaining` and hide this field from non-admin users.
- fix display of `total number of task runs remaining` and `total number of tasks available for you`
Manually tested
=> 2441 - fix display numbers of tasks/taskruns on info page

pybossa/api/__init__.py, settings_test.py.tmpl, test/default.py, test/helper/web.py, test/test_api/test_project_api.py
- Added chat integration with Slack and Chatlio.
For a specific list of projects by `short_name` or `all`.
```
CHAT_ENABLE = ['all']
CHAT_URL = 'https://gigwork-dev.slack.com'
```
```
CHAT_ENABLE = ['project1', 'project2']
CHAT_URL = 'https://gigwork-dev.slack.com'
```
Related https://github.com/bloomberg/pybossa-default-theme/pull/218
=> RDISCROWD-893 Chat integration

pybossa/view/projects.py, test/test_view/test_project_clone.py
- Replace all instances of old_name in the task presenter HTML with new_name when cloning a project.
=> Replace short name that is between [' or"]

pybossa/api/__init__.py, settings_local.py.tmpl, settings_test.py.tmpl, test/test_quiz_mode.py
- Allow scheduling a gold-only task if quiz mode is enabled for the user and the project.
=> RDISCROWD-2636 Turning off project quiz mode should allow users normal tasks

pybossa/forms/forms.py, pybossa/forms/validator.py, test/test_forms.py
Validation of date against being in the future was not working because it was using a single static date value to validate against.
Manual
=> Reject date in the future.

pybossa/forms/validator.py, test/test_forms.py, test/test_web.py
- Resolves an issue with duplicate users by name and email address, due to whitespace included within the name.
_".. admin user export csv file that the following people have two accounts with the same usernames and email addresses.. It appears that the names and fullnames have some bad characters at the end."_
=> RDISCROWD-2065 Prevent whitespace in form submissions

pybossa/cache/projects.py, pybossa/forms/forms.py, pybossa/forms/projects_view_forms.py, pybossa/jobs.py, pybossa/model/event_listeners.py, pybossa/repositories/task_repository.py, pybossa/view/projects.py, test/test_jobs/test_progress_reminder.py, test/test_view/test_project_progress_reminder.py
*Issue number of the reported bug or feature request: #<2835>*
https://jira.prod.bloomberg.com/browse/RDISCROWD-2835
The number remaining tasks will changed by following events: 
- add new tasks
- worker submits tasks
- decrease/increase task redundancy
- delete incomplete tasks
Email should be sent upon there're less than N tasks left incomplete (N is configured by project owner)
Calling `check_and_send_project_progress` in each of events above, `check_and_send_project_progress ` does:
- check if reminder is enabled;
- calculate # remaining tasks;
- send email and mark flag `sent = True` if there're <= N remaining tasks 
- mark `sent = False` if there're more than N remaining tasks
=> Task reminder

pybossa/jobs.py, pybossa/view/projects.py, test/test_jobs/test_import_tasks.py
*Issue number of the reported bug or feature request: #<2988>*
https://jira.prod.bloomberg.com/browse/RDISCROWD-2988
Bug issue: 
`import_task` function returns before re-activating task notification.
Additional change: 
For the usecase where task file is too large to import synchronously, importing job is placed in job queue. In this case we are not able to activate task notification synchronously, instead, reactivate after the job is picked up by background worker and executed successfully.
=> task-notification fix

pybossa/util.py, test/test_util.py
- Added validation of integers for required fields when importing via CSV, as configured in settings_local.py (`data_owner` and `data_source_id`).
- Prevents values in CSV imports of `123.0`, `abc`, `456.78` when enabled.
- New option `require_int: True` (if omitted, values will not be enforced to be integers).
- Added unit tests.
```python
TASK_REQUIRED_FIELDS = {
'data_owner': {'val': None, 'check_val': False, 'require_int': True},
'data_source_id': {'val': None, 'check_val': False, 'require_int': True}
}
```
=> RDISCROWD-3077 Import CSV require integers for data_owner, data_source_id

pybossa/util.py, test/test_util.py
- Added fix for validate_required_fields() when a value is an integer (not a string).
- Added unit test to handle case.
```text
Traceback (most recent call last):
/home/____/.local/lib/python2.7/site-packages/nose/case.py line 197 in runTest
self.test(*self.arg)
test/default.py line 43 in decorated_function
return f(*args, **kwargs)
test/test_util.py line 676 in test_integer_required_cast_string
invalid_fields = util.validate_required_fields(data)
pybossa/util.py line 1099 in validate_required_fields
(int_val and ('.' in import_data or not is_int(import_data))):
TypeError: argument of type 'int' is not iterable
```
```text
Test importing an integer (non-csv) with validate_required_fields. ... passed
---------- coverage: platform linux2, python 2.7.15-final-0 ----------
Coverage HTML …
```
=> Fix for required_field_validator on an integer value.

pybossa/cache/helpers.py, pybossa/redis_lock.py, pybossa/sched.py, pybossa/view/projects.py, test/test_sched_2.py
- Added number of tasks in progress to the project summary page.
Re: https://github.com/bloomberg/pybossa-default-theme/pull/273
=> RDISCROWD-3112 Number of locked tasks for tasks in progress

pybossa/data_access.py, pybossa/forms/dynamic_forms.py, test/test_api/test_project_api.py
*Issue number of the reported bug or feature request: #<3031>*
https://jira.prod.bloomberg.com/browse/RDISCROWD-3031
- add js code to `/update` and `/new` page so that if the user chooses L1 for either input_data_class or ourput_data_class, uncheck opt-in checkbox 
- modify create-project API method so that if the user chooses L1, set opt-in False
Re: https://github.com/bloomberg/pybossa-default-theme/pull/275
=> RDISCROWD-3031 - default optout L1 projects

pybossa/view/bloomberg.py, test/test_view/test_bloomberg.py
https://jira.prod.bloomberg.com/browse/RDISCROWD-3173
https://jira.prod.bloomberg.com/browse/RDISCROWD-3143
I added a conditional to the response handler in bloomberg.py to create a new basic Gigwork account with values return by a successful BSSO if no account exists.
I tested for a few different scenarios and confirmed that existing BSSO and login functionality would not be affected.
=> RDISCROWD-3173: auto-generate new account from BSSO login

test/test_view/test_bloomberg.py
Issue number of the reported bug or feature request: #
https://jira.prod.bloomberg.com/browse/RDISCROWD-3173
Describe your changes
Tests test_login_create_account_success and test_login_create_account_fail in test_bloomberg.py were ineffective because patches were improperly defined. I fixed these.
@patch('pybossa.view.account.create_account', autospec=True) should have been @patch('pybossa.view.bloomberg.create_account', autospec=True)
@patch('pybossa.view.account._sign_in_user', autospec=True) wasn't being used anyways so I took it out
=> RDISCROWD-3173: Fixed Patches on Tests

pybossa/view/bloomberg.py, test/test_view/test_bloomberg.py
https://jira.prod.bloomberg.com/browse/RDISCROWD-3216?filter=-1
I updated the fields used to create new accounts from BSSO login information so that the syntax would match the new return. See DRQS 160388426 for more details on the BSSO update.
I updated the mocks to reflect the syntax of the new return and tested the modules locally.
=> RDISCROWD-3216: Update auto-create account fields for new BSSO return

pybossa/forms/forms.py, pybossa/view/account.py
https://jira.prod.bloomberg.com/browse/RDISCROWD-3134
The ProjectCommonForm and ProjectUpdateForm passwords were both TextFields instead of Password fields. I changed this and also added type="password" to the render_field in the html for projects/new.html and projects/update.html. 
I checked to see that these fields were rendering correctly locally.
***Screenshot***
=> RDISCROWD-3134: Hide Password in Project Settings Password Field

pybossa/util.py, pybossa/view/account.py, pybossa/view/bloomberg.py, test/test_view/test_bloomberg.py
https://jira.prod.bloomberg.com/browse/RDISCROWD-3216
Tim requested that an email be sent to his account when an account is created via the BSSO route, as well as to display a flash message to the user indicating that a new account has been created for them using BSSO. This required adding the conditional to send the message, the message creation function, the message html/md, and the related test.
I added a new test and also tested locally.
=> RDISCROWD-3216: BSSO account creation alert

pybossa/view/bloomberg.py
https://jira.prod.bloomberg.com/browse/RDISCROWD-3216?filter=-1
Bug fix for merged branch RDISCROWD-3216. We needed to pass the data access level at the time of account creation which is required for prod. This is why it was working in dev but failing in prod.
Tests pass and I was able to create an account without issue locally.
=> add default data access level

pybossa/view/bloomberg.py
https://jira.prod.bloomberg.com/browse/RDISCROWD-3221
Changing data type of data access field to list to address the following datatype error (single field being parsed because it's not a list):
flask.app:ERROR:[2020-06-25 13:11:00,845] Auto-account creation error: Invalid access levels L, 4, for user attributes: {'username': ['acianciara'], 'uuid': ['5641377'], 'firstName': ['Anna'], 'lastName': ['Cianciara'], 'firmId': ['9001'], 'emailAddress': ['acianciara@bloomberg.net']} [in /opt/bb/libexec/python-gigwork-env/pybossa/pybossa/view/bloomberg.py:97]
Local tests are passing.
=> RDISCROWD-3221: Bug fix - data access field type

pybossa/cache/site_stats.py, pybossa/view/admin.py
*Issue number of the reported bug or feature request: #<3045>*
https://jira.prod.bloomberg.com/browse/RDISCROWD-3045
The problem is that monthly data was sorted in ascending order by date, and it selects the first 24 records (2 years), this brings us the *oldest* 24 datapoints.
It should be sorted in descending order by date so we got the latest 24 datapoints instead of oldest 24 datapoints
=> RDISCROWD-3045 Fix Management board statistics error 

pybossa/api/project.py, pybossa/repositories/project_repository.py, test/test_api/test_project_api.py
*Issue number of the reported bug or feature request: RDISCROWD-3296*
info.data_access field is created upon saving a project model, but the project api currently tries to check for it before that. This sets a default that lets the api do its check and the correct data_access to be set upon saving.
- updated and ran unit tests
- added test to ensure data access is updated correctly
=> Fix bug with project api data access field being checked before creation

pybossa/util.py, pybossa/view/projects.py
- Fixed failing unit tests in `util.py` due to `misaka`.
Fixes the following tests from failing:
```bash
./run_tests test/test_api/test_project_api.py:TestProjectAPI.test_project_post_desc_from_long_desc -s
./run_tests test/test_util.py:TestPybossaUtil.test_is_int -s
```
=> Added fix for unit tests failing due to misaka.

pybossa/api/project.py, test/test_api/test_project_api.py, test/test_syncer/__init__.py, test/test_syncer/test_project_syncer.py
Issue number of the reported bug or feature request: #RDISCROWD-3395
- Updated api for projects so password is not required for sync requests. This method was chosen instead of changing the syncer to prevent having to use multiple API queries to sync a new project, since the current API requires one call to create with password and another to replace the passwd_hash. 
- Updated and ran unit tests
- Added integration tests between syncer and api
- Couldn't get tests to work on locally running pybossa instance
**Additional Notes**
Test setup change due to issue related to https://github.com/bloomberg/pybossa/pull/505
`http_signer`, similar to `misaka`, isn't made a global variable until the app is setup. This is done as part of the setUp …
=> RDISCROWD-3395: Project sync to prod fails due to password error

pybossa/core.py
Issue number of the reported bug or feature request:  RDISCROWD-2186
- Removed extra period from timeout warning message
None, didn't want to wait for a timeout :)
=> RDISCROWD-2186: removing extra period from timeout warning

pybossa/view/projects.py, test/test_view/test_project_new.py
The issue occurs testing locally when current_app.config.get('DATA_CLASSIFICATION') returns alternate value ('', False), which is a tuple. And the unpacking variables data_class, enabled  in the for loop are expecting a tuple in an iterable. 
Changing ('', False) to [('', False)] so it becomes a list of tuples and make both for loop and unpacking happy.
Tested locally and this approach works.
None
=> fixing a dict alternate value issue in the for loop

pybossa/forms/dynamic_forms.py, pybossa/forms/validator.py, pybossa/repositories/project_repository.py, settings_test.py.tmpl, test/test_api/test_project_api.py, test/test_forms.py
With opt-in for annotations to be stored on AMP, Project PVF to be required for projects with data access levels as L1/L2.
For L3, L4 annotations, generic pvf to be configured.
=> RDISCROWD-3470: AMP PVF to be set as per projects data access levels

pybossa/cloud_store_api/s3.py
*Issue number of the reported bug or feature request: RDISCROWD-3584*
Added audio/mpeg and audio/wav MIMe type to support uploading mp3 and wav audio in the task presenter
Tested locally
=> RDISCROWD-3584 Add Content-Types to BCOS Upload Python Script

pybossa/view/fileproxy.py, test/test_view/test_fileproxy.py
- task.info can have field named `private_json__encrypted_payload` that contains stringified json payload in encrypted form.
- the encryption key is stored under BPV and BPV id is submitted under project settings.
- when presenting task, client can make call to `/encrypted/taskpayload/<int:project_id>/<int:task_id>`
- encrypted data would be decrypted by this new endpoint taking encryption key from project settings.
- response returned by this new endpoint would contain decrypted stringified json that can be appended to task.info under task presenters onPresentTask
=> RDISCROWD-3744: Encrypted task payload

pybossa/cache/users.py, pybossa/jobs.py
Rdiscrowd 3774 Admin Stats Dashboard Not Matching User Report
Changed the column name in the user report from completed_tasks to completed_task_runs
ran local gigwork and confirmed that the change was made properly by exporting a user report
this was a bug fix for an instance where the completed_tasks col on the user report was actually displaying completed_task_runs
=> Rdiscrowd 3774 Admin Stats Dashboard Not Matching User Report

pybossa/forms/forms.py
- Added warning message to Task Preferences form field.
- Renamed label from "Profiles(json format)" to "Task Preferences".
=> RDISCROWD-4287 Task Preferences warning message

pybossa/cache/users.py, test/test_cache/test_cache_users.py
*Issue number of the reported bug or feature request: RDISCROWD-4347*
When the system selects tasks, the call chain is: [select_contributable_task](https://github.com/bloomberg/pybossa/blob/3da998fcb56489bb3ba9c9e0f42b4fa2faeb10e5/pybossa/sched.py#L378) -> [locked_task_sql](https://github.com/bloomberg/pybossa/blob/3da998fcb56489bb3ba9c9e0f42b4fa2faeb10e5/pybossa/sched.py#L387) -> [get_user_filter](https://github.com/bloomberg/pybossa/blob/3da998fcb56489bb3ba9c9e0f42b4fa2faeb10e5/pybossa/sched.py#L325). get_user_filter is [cached for one day](https://github.com/bloomberg/pybossa/blob/3da998fcb56489bb3ba9c9e0f42b4fa2faeb10e5/pybossa/cache/users.py#L360). When saving a meta, although it [clears the cache](https://github.com/bloomberg/pybossa/blob/3da998fcb56489bb3ba …
=> RDISCROWD-4347 Refresh Cache When Updating User Profile Information on Private and Public Platforms

pybossa/api/task.py, test/test_admin.py
https://jira.prod.bloomberg.com/browse/RDISCROWD-4427
This is to replay exporting tasks in order to support a valid use case described under 4427 wherein tasks were originally a regular task(but incomplete, hence not added to user buckets) when converted to gold, export task data to user bucket.
=> RDISCROWD-4427 enable API to mark gold task exported=false

pybossa/forms/forms.py, pybossa/view/projects.py, test/test_view/test_project_timeout.py
- Increase task timeout from 120 to 210.
- Fixed typo *minuntes* to *minutes*.
```text
test_view.test_project_timeout.TestProjectTimeout.test_set_timeout_too_high_minutes ... passed
test_view.test_project_timeout.TestProjectTimeout.test_set_timeout_too_high_seconds ... passed
test_view.test_project_timeout.TestProjectTimeout.test_set_timeout_too_low ... passed
test_view.test_project_timeout.TestProjectTimeout.test_set_timeout_value ... passed
---------- coverage: platform linux2, python 2.7.15-final-0 ----------
Coverage HTML written to dir htmlcov
-----------------------------------------------------------------------------
7 tests run in 147.707 seconds (7 tests passed)
```
=> RDISCROWD-4424 Increase task timeout from 120 to 210.

pybossa/view/account.py, test/test_view/test_user_import.py
- Fixed bug on **User Type** when importing users from csv.
*Changed `user_type` to be read from `user_data.metadata`*
```csv
name,fullname,email_addr,project_slugs,metadata
Alice.Doe,Alice Doe,alice.doe@null.com,,"{""user_type"": ""Generic Vendor""}"
```
=> RDISCROWD-4654 Fix for User Type when Importing Users CSV

pybossa/view/projects.py
- Allow toggle between browse tasks and task list views.
Re: https://github.com/bloomberg/pybossa-default-theme/pull/329
=> RDISCROWD-4747 Allow toggle between browse tasks and task list views.

pybossa/view/projects.py
- Allow admin/subadmin/coowner from tasklist view to submit tasks (not read-only mode).
Re: https://github.com/bloomberg/pybossa-default-theme/pull/330
=> RDISCROWD-4747 Allow submitting tasks by admin/sub/owner in task list view

pybossa/cache/__init__.py, test/test_cache/__init__.py
- Set minimum redis timeout to 1 second.
- Fix for `redis.exceptions.ResponseError` when setting a value of `0` for a cache timeout value.
1. Edit default_settings.py and change line 82:
```python
USER_TIMEOUT = 0 #15 * 60
```
See also [here](https://serverfault.com/questions/682801/redis-and-invalid-expire-time-in-setex).
=> Fix for redis.exceptions.ResponseError: invalid expire time in setex

pybossa/api/api_base.py, pybossa/cache/announcements.py
- Clear announcements cache when updating an announcement.
- Fixes bug with user-level workers seeing admin-level announcements during cache period of announcement between saves.
=> RDISCROWD-4793 Fix announcements permission to clear cache

pybossa/api/__init__.py, pybossa/cache/helpers.py, pybossa/redis_lock.py, pybossa/sched.py, test/test_reserve_task_category.py, test/test_web.py
=> RDISCROWD-4705: Reserve task category

pybossa/exporter/__init__.py, pybossa/exporter/csv_export.py, pybossa/exporter/csv_reports_export.py, pybossa/exporter/project_csv_export.py, pybossa/exporter/task_csv_export.py, pybossa/exporter/task_json_export.py, pybossa/forms/forms.py, pybossa/jobs.py, pybossa/util.py, test/test_project_report.py
I used pandas to do CSV export instead of using "UnicodeWriter" in the util.py. The "UnicodeWriter" is difficult to maintain and work right in Python3. Also using Pandas, the code is conciser. Now, the only place still using "UnicodeWriter" is the tasks exporting. There is some work to get rid of "UnicodeWriter" for task exporting, so I just leave there. But I have tested and made changes to make sure the export works (verify the file in temp path).
=> fix project report and user csv exporting

.github/workflows/github-actions.yml, setup.py
*Issue number of the reported bug or feature request: RDISCROWD-4850*
- change psycopg2-binary to psycopg2 per [recommendation](https://www.psycopg.org/docs/install.html#psycopg-vs-psycopg-binary). Also downgrade the version to make consistent.
- Github Actions to change to disable annotations alert.
Tested locally
=> RDISCROWD-4850 Change to use psycopg2 2.8.6 version

pybossa/cache/project_stats.py, pybossa/util.py, test/test_cache/test_cache_project_stats.py
*Issue number of the reported bug or feature request: RDISCROWD-4906*
The original complicated multiple JOIN SQL is really to select all tasks with at least 1 task run and its last finish time. So we can simply get this info from task_run table.
The runtime upon Prod size data(10 million records in task_run) is ~1.3s. The main reason it is still quite slow is because the type of "finish_time" column is text, not timestamp. Thus applying the a function to a column makes index not working, not mentioning there is no index for column "finish_time". Adding an index and changing the column type will be future work. We leave it for now to keep 1.3s query time and utilize cache to compensate the slow query.
Local and public QA
**Performance** …
=> RDISCROWD-4906 Optimize stats_dates method used in project_by_shortname

pybossa/sched.py
- Added check to load task_project_id if missing from cache.
=> RDISCROWD-4924 Bug fix for missing task_project_id in redis cache to load from db.

alembic/versions/ed775af5e086_rdiscrowd_4967_add_partial_index_for_.py
*Issue number of the reported bug or feature request: RDISCROWD-4967*
Add a partial index for task table based on the two slow SQLs
**Test machine**: Mac Pro with 5M records of task table and 10M records of task_run table(half volume of Prod but Prod servers are more powerful)
The SQL 1 tasks **32s**(without a partial index), very close to 34s in Prod, see the following explain plan screenshot.
With a partial index added, the execution time from explain plan reduces to **~3ms**(actual SQL with data could be ~60ms), screenshot as follows:
The running time from explain plan of SQL 2 reduces to a **0.1ms**(actual SQL with data could be ~60ms)
**Insert Performance Impact**
The test in the local machine showed the impact of adding partial index …
=> RDISCROWD-4967 Optimize slow queries used by Gigwork poller

.gitignore, pybossa/cache/__init__.py, pybossa/cache/projects.py, test/test_cache/__init__.py
*Issue number of the reported bug or feature request: RDISCROWD-4904*
Create a new decorator for caching such that when cache miss occurs, only one request is allowed to query the DB. This will greatly reduce the DB load, especially when the DB operation is heavy. Also, longer TTL level 2 cache is used in case of level 1 cache miss. The request can still return a data fast from level 2 cache.
Tested locally. Also two unit tests were added([here](https://github.com/bloomberg/pybossa/blob/f8224d6a24a0b4a86c827fa8ab4cb1995693f45a/test/test_cache/__init__.py#L679) and [here](https://github.com/bloomberg/pybossa/blob/f8224d6a24a0b4a86c827fa8ab4cb1995693f45a/test/test_cache/__init__.py#L731)) to compare the behavior of the existing decorator and …
=> RDISCROWD-4904 fix gigwork cache miss - step 2

pybossa/redis_lock.py
- Load task_project_id if not in cache.
Added same fix as found [here](https://github.com/bloomberg/pybossa/blob/python3.9/pybossa/sched.py#L772-L774) and [here](https://github.com/bloomberg/pybossa/blob/python3.9/pybossa/sched.py#L684-L686).
=> RDISCROWD-5080 Load task_project_id if not in cache

pybossa/view/projects.py, test/test_view/test_project_transferownership.py
- Retain coowners when transferring project ownership.
- Added unit tests.
```text
(env3) /mnt/c/Projects/gigwork/pybossa$ nosetests 'test/test_view/test_project_transferownership.py:TestProjectTransferOwnership.test_transfer_retain_coowners' -s
Test transfer ownership retains existing coowners after transfer to new owner. ... passed
----------- coverage: platform linux, python 3.9.5-final-0 -----------
Coverage HTML written to dir htmlcov
-----------------------------------------------------------------------------
1 test run in 30.246 seconds (1 test passed)
```
```
(env3) /mnt/c/Projects/gigwork/pybossa$ nosetests 'test/test_view/test_project_transferownership.py:TestProjectTransferOwnership.test_transfer_retain_coowners_multi' -s
Test transfer ownership retains existing coowners …
```
=> RDISCROWD-5093 Retain coowners when transferring project ownership.

pybossa/api/__init__.py, pybossa/redis_lock.py, pybossa/sched.py, test/test_reserve_task_category.py, test/test_web.py
*Issue number of the reported bug or feature request: RDISCROWD-4870*
Add an endpoint for the front-end to call to release category locks. 
The call stack is as follows:
Click "Submit and Leave" (or "Submit") button -> pybossa-vue/app.js/submit() -> pybossa.js/saveTask() -> pybossa.js/_createTaskRun() -> pybossa.js/_saveTaskRun -> API POST call to 'api/taskrun' or 'api/project/<projectId>/taskgold' -> event_listeners.py/on_taskrun_submit() -> sched.py/after_save() -> sched.py/release_reserve_task_lock_by_id()
Tested locally
https://github.com/bloomberg/pybossa.js/pull/14
https://github.com/bloomberg/pybossa-default-theme/pull/361
https://bbgithub.dev.bloomberg.com/GIGwork/pybossa-vue/pull/117
=> RDISCROWD-4870 Task Reservation should be released upon submit and leave

pybossa/importers/csv.py, test/test_util.py
- Allow case-insensitive required CSV column names.
- Added unit test.
=> RDISCROWD-5193 Allow case-insensitive required column names in CSV import

create_bulk_tasks.py, pybossa/api/__init__.py, pybossa/api/bulktasks.py, pybossa/repositories/task_repository.py, test/test_api/test_bulktasks_api.py
* add option to createbulktask script so that tasks can be created for current year
* new api `/api/bulktasks` to updata task priority of tasks in bulk. expected payload to pass along is list of dict containing `task id` and `priority` values
=> RDISCROWD-5196: Add new api bulktasks

pybossa/api/bulktasks.py, pybossa/repositories/task_repository.py
Similar to updating task priorities via bulktasks [here](https://github.com/bloomberg/pybossa/blob/main/pybossa/repositories/task_repository.py#L195), reset cache so that latest priority updates are available immediately instead of after cache rebuild that cause lag in user experience with priority updates.
=> RDISCROWD-5251: Reset cache upon bulktasks update

pybossa/api/__init__.py, pybossa/sched.py, test/test_api/test_project_api.py
*Issue number of the reported bug or feature request: RDISCROWD-5270
Describe your changes
In cherry-pick mode, when user click a task, this change will pass the task id all way down to the API, instead of relying on the longest TTL in the cache to get the task
Testing performed
Tested locally
Additional context
related prs:
https://github.com/bloomberg/pybossa.js/pull/15
https://github.com/bloomberg/pybossa-default-theme/pull/372
=> RDISCROWD-5270 Wrong Task Being Accessed Via Task List When Multiple Tasks Locked

pybossa/view/projects.py
- Added audit log when adding coowner to a project.
|When	|Who	|Source	|Action	|Attribute	|Old Value	|New Value|
|-----------|----------|----------|-----------|----------|----------------|-----------|
|2022-08-03T19:11:17.749298	|You	|web	|update	|project.coowners	|{1,2,3}	|[1]|
|2022-08-03T19:11:10.519822	|You	|web	|update	|project.coowners	|{1,2}	|[1, 2, 3]|
|2022-08-03T19:10:44.110738	|You	|web	|update	|project.coowners	|{1}	|[1, 2]|
|2022-08-03T19:10:34.775497	|You	|web	|update	|project.coowners	|{1,2}	|[1]|
=> RDISCROWD-5091 Added audit log when adding coowner to a project

pybossa/redis_lock.py, pybossa/sched.py, settings_test.py.tmpl, test/test_api/test_project_api.py, test/test_locked_sched.py
*Issue number of the reported bug or feature request: RDISCROWD-5170*
Add a mutex in acquire_lock function so that only one request can perform update Redis hash at a time.
Using multiple threads in the unit tests to simulate concurrent users. With the unit tests, the race condition could be reproduced before the fix.
=> RDISCROWD-5170 fix race condition

pybossa/cache/projects.py
converting date in string form from utc to est is resource intensive causing max time for processing task browse request; 95% of time spend on converting utc -> est bulk tasks(~25k) that will be thrown away as tasks are dynamic. Instead, only format date for max number of tasks that can be displayed to the user.
=> RDISCROWD-5378: Task browse perf. format date utc -> est

pybossa/view/projects.py
- Fixed incorrect value in audit log from /assign-users.
=> Audit log - Fixed incorrect value in audit log from assign-users

pybossa/util.py, pybossa/view/projects.py, test/test_util.py
*Issue number of the reported bug or feature request: RDISCROWD-5372*
- Disable "autosave" in response reviewing mode (doesn't affect "autosave" when submitting the task)
- Consider user can use both "v-bind:data" and shorthanded ":data" for data binding to make the code more robust.
tests performed locally and worked as desired.
The initial investigation due to cache is not correct. The root cause of different users seeing the same response is because the TP code has "autosave" enabled, so that the first opened response is saved to browser's IndexedDB. Thus the following response is reading from the browser's IndexedDB.
=> RDISCROWD-5372 User responses looks the same even they did not give the same answer

pybossa/view/projects.py, test/test_coowners.py
- Added parameter to allow searching for contacts against coowners, admin, subadmin.
Re: https://github.com/bloomberg/pybossa-default-theme/pull/376
=> RDISCROWD-5412 Search contacts against coowners, subadmin, admin.

pybossa/view/projects.py, test/test_view/test_assign_task_worker.py
*Issue number of the reported bug or feature request: RDISCROWD-4878*
Skip gold task for bulk assign users, but allow single assign users for gold task.
Related pr: https://github.com/bloomberg/pybossa-default-theme/pull/377
=> RDISCROWD-4878 ask browse bulk edit state not updating

pybossa/cache/task_browse_helpers.py, test/test_cache/test_task_browse_helpers.py
*Issue number of the reported bug or feature request: RDISCROWD-4878*
When filter is passed for bulk assigning workers, there was an exception causing the "assign users" list to be empty. 
Tested locally
=> fixing assign users' list is empty

pybossa/cache/helpers.py
- Performance improvement to avoid SQL query from `n_available_tasks_for_user` when the task scheduler is `task-queues`.
Re: https://github.com/bloomberg/pybossa/pull/789
=> return the magic number 10; using ad65572 commit id of pybossa-default-theme

pybossa/cache/projects.py, pybossa/cache/task_browse_helpers.py, test/test_cache/test_cache_projects.py
=> RDISCROWD-4871: Add assigned users column under task browse

pybossa/api/task.py, pybossa/api/task_run.py, pybossa/auth/taskrun.py, test/test_api/test_task_api.py, test/test_api/test_taskrun_api.py, test/test_authorization/test_taskrun_auth.py
This PR will enable admin and users to edit their submissions. Enable admin for updating submissions such as `__upload_url` when moving files to bucket that has extended expiration upon task completion.
=> RDISCROWD-5627: Allow editing of taskruns

pybossa/util.py, test/test_util.py
*Issue number of the reported bug or feature request: RDISCROWD-5653*
- Using ```document.getElementById("annex-viewer")``` or ```document.getElementById("shell-container")``` to identify Annex shell instead of ```shell.setAttribute("hash", "anything");``` because Annex doesn't always have to set hash attribute.
- For "table-element", if the existing data contains a list of javascript object and ```task.info.some_attribute``` in the object, the code will parse the  ``task.info.some_attribute``` and get the corresponding data for it.
- Exception handling added.
None
=> RDISCROWD-5653 Bug With Showing Completed Answers

pybossa/cache/task_browse_helpers.py, pybossa/view/projects.py, test/test_cache/test_cache_projects.py, test/test_web.py
* Enable browse task for regular user only when project is configured to allow edit submissions.
* Show only completed tasks by regular user under browse tasks.
=> RDISCROWD-5651: Enable browse task for regular user

pybossa/forms/forms.py, pybossa/view/projects.py, test/test_web.py
=> RDISCROWD-5627: Disable edit submission based on instance type

pybossa/api/api_base.py, pybossa/api/project.py, pybossa/view/projects.py, test/test_api/test_project_api.py, test/test_web.py
- Enforce size limit for task presenter HTML.
- Added check to view/projects.py (task presenter update from web page).
- Added check to api/project.py (task presenter update from PUT request).
- Size limit is configurable via settings_local.py value `TASK_PRESENTER_MAX_SIZE_MB`, default to 2 MB.
=> RDISCROWD-5733 Enforce size limit for task presenter HTML

pybossa/cache/__init__.py, pybossa/cache/site_stats.py, pybossa/jobs.py, pybossa/settings_local.py.tmpl, pybossa/view/admin.py, test/test_admin.py, test/test_cache/test_site_stats.py
*Issue number of the reported bug or feature request: [RDISCROWD-5739](https://jira.prod.bloomberg.com/browse/RDISCROWD-5739)*
Adds a new admin usage dashboard that displays totals for following fields:
1. Total projects
2. Total tasks
3. Total taskruns
4. Total projects using NLP component (text-tag)
5. Total projects using annex
6. Total projects using DocX
**Usage**
Takes url parameter 'months' to specify how many previous months to include in the stats. Examples: http://localhost:5000/admin/usage_dashboard/?months=12
http://localhost:5000/admin/usage_dashboard/?months=24
http://localhost:5000/admin/usage_dashboard/?months=123
etc...
**settings_local Config example:**
```
USAGE_DASHBOARD_COMPONENTS = {
'Annex' : 'annex-shell',
'DocX' : 'loadDocument',
'NLP Component' : 'text-tagging'
} …
```
=> RDISCROWD-5739 Admin Usage Dashboard

pybossa/api/__init__.py, pybossa/cache/projects.py, pybossa/sched.py, pybossa/util.py, pybossa/view/projects.py, test/test_cache/test_cache_projects.py, test/test_sched.py, test/test_util.py, test/test_web.py
*Issue number of the reported bug or feature request: RDISCROWD-5631*
- /project/<shortname>/new_task API now accepts saved_task_position=first or saved_task_position=last to indicate the saved tasks should be placed at the head of the queue or at the tail of the queue
- Task list will always display the saved tasks first
- partial_answer API's endpoint has been updated to include project_shortname. Also, a sorted set is used to track all tasks IDs saved by the user.
- /project/<short_name>/has_partial_answer API is added to check whether a user has any saved tasks for the project
Tested locally
Related PRs:
- https://github.com/bloomberg/pybossa.js/pull/24
- https://github.com/bloomberg/pybossa-default-theme/pull/407
=> RDISCROWD-5631 Retrieving partially saved tasks from a different queue

pybossa/api/project.py
- Added fix for None content length: `'>' not supported between instances of 'NoneType' and 'int'`
*The missing `request.content_length` appears to occur when issuing a PUT request to **http://** instead of **https://**.*
PUT http://qa.gigwork.net/api/project/1887
```json
{
"info": {
"task_presenter": "acb123...",
"task_guidelines": "",
"data_classification": {
"input_data": "abc",
"output_data": "xyz"
}
}
}
```
```json
{
"action": "PUT",
"status": "failed",
"status_code": 415,
"target": "project",
"exception_cls": "TypeError",
"exception_msg": "'>' not supported between instances of 'NoneType' and 'int'"
}
```
=> Project API fix - Added None check on content length when size exceeds limit.

pybossa/api/api_base.py, pybossa/api/task.py, test/test_api/test_task_api.py
*Issue number of the reported bug or feature request: [RDISCROWD-5775](https://jira.prod.bloomberg.com/browse/RDISCROWD-5775)*
Modifies the task API so that task expiration cannot be set beyond the permitted max expiration (60 days for private and 180 days for public) using a PUT request.
If the user tries to set task expiration beyond the limit, it is set to the maximum possible expiration and the method returns a 200 response code.
Tested Locally
=> RDISCROWD-5775 limit task expiration

pybossa/cache/users.py, pybossa/view/account.py, test/test_web.py
*Issue number of the reported bug or feature request: [RDISCROWD-5743](https://jira.prod.bloomberg.com/browse/RDISCROWD-5743)*
Add new API methods:
1. `GET /<user_name>/taskbrowse_bookmarks/<short_name>`: get a list of the user's bookmarks for the specified user and project.
Response JSON: 
`{ name1: url1, name2: url2...}`
2. `POST /<user_name>/taskbrowse_bookmarks/<short_name>`: add a new bookmark for the specified user and project.
Request JSON:
`{name: <new bookmark name>, url: <new bookmark url>}`
Response JSON: new list of bookmarks
`{ name1: url1, name2: url2...}`
3. `DELETE /<user_name>/taskbrowse_bookmarks/<short_name>`: delete the specified bookmark by name
Request JSON:
`{name: <bookmark to delete>}`
Response JSON: new list of bookmarks
`{ name1: url1, …
=> RDISCROWD 5743 task browse bookmarks

pybossa/api/task.py, pybossa/importers/importer.py, pybossa/repositories/task_repository.py, pybossa/task_creator_helper.py, pybossa/util.py, test/test_api/test_task_api.py, test/test_task_creator_helpers.py
*Issue number of the reported bug or feature request: [RDISCROWD-5852](https://jira.prod.bloomberg.com/browse/RDISCROWD-5852)*
**Previously**
In https://github.com/bloomberg/pybossa/pull/830, we limited the task expiration based on the current date. The task expiration limit was _n_ days from the current day. This allowed for the user to indefinitely extend their tasks' expirations, which we don't want.
**Now**
Task expiration limit is now _n_ days from the create date of the task, putting a hard cap on task expiration.
Tested locally
https://github.com/bloomberg/pybossa/pull/830
=> RDISCROWD-5852 Calc task expiration by create date

pybossa/api/__init__.py, test/test_api/__init__.py
*Issue number of the reported bug or feature request: RDISCROWD-5843*
Add a new endpoint for LLM
Test locally.
=> RDISCROWD-5843 GIGWork GPT Helper Component MVP (v1) - Backend

pybossa/view/projects.py, test/test_web.py
*Issue number of the reported bug or feature request: [RDISCROWD-5704](https://jira.prod.bloomberg.com/browse/RDISCROWD-5704)*
Adds a completed column for workers on the task browse screen.
=> RDISCROWD-5704 Completed col in workers task browse

pybossa/view/account.py, pybossa/view/projects.py, test/test_web.py
*Issue number of the reported bug or feature request: [RDISCROWD-5851](https://jira.prod.bloomberg.com/browse/RDISCROWD-5851)*
Adds `created` and `updated` fields for each bookmark. New data structure in DB:
```
user.info = { 
metadata...,
taskbrowse_bookmarks : {
project_name : {
bookmark_name : {
url: http://localhost:5000/project/proj/...
created: 2023-04-05T17:59:28.516927
updated: 2023-04-05T17:59:28.516927
}
....
},
project_name : {
bookmark_name : {...,
bookmark_name : {...,
bookmark_name : {...
....
}
...
}
}
```
Example endpoint JSON response structure:
```
[
{
"created": "2023-04-26T18:17:29.745312",
"name": "apple",
"updated": "2023-04-26T18:17:29.745320",
"url": "http://localhost:5000/project/testproject2/tasks/browse"
},
{
"created": …
```
=> Rdiscrowd 5851 taskbrowse bookmarks dates

pybossa/view/account.py, pybossa/view/projects.py, test/test_coowners.py
*Issue number of the reported bug or feature request: [RDISCROWD-5742](https://jira.prod.bloomberg.com/browse/RDISCROWD-5742)*
All `/taskbrowse_bookmarks` API calls return an updated list of bookmarks. 
- POST adds a bookmark to the list and the API response is an updated list
- DELETE removes a bookmark from the list and the API returns an updated list
- GET gets the current list of bookmarks
This PR adds 2 new optional url query parms, `order_by` and `desc` to specify the order of the resultant lists. Options are 
- `order_by` = name, updated, or created
- `desc`  = true/ false
The default sort is by alphabetically by bookmark name.
Example query:
http://localhost:5000/account/user/taskbrowse_bookmarks/testproject2?order_by=created&desc=true
Example response: …
=> RDISCROWD-5742 sorting saved filters list

pybossa/cache/task_browse_helpers.py
*Issue number of the reported bug or feature request: [RDISCROWD-5998](https://jira.prod.bloomberg.com/browse/RDISCROWD-5998)*
Show new spelling of Türkiye in location pickers. Support both spellings on backend.
=> RDISCROWD-5998 support alternate turkey spelling

pybossa/cache/task_browse_helpers.py, pybossa/util.py, test/test_util.py
*Issue number of the reported bug or feature request: [RDISCROWD-6042](https://jira.prod.bloomberg.com/browse/RDISCROWD-6042)*
Backwards compatible turkey spelling. Support Türkiye, Turkiye, or Turkey in CSV task upload.
Any combination or Turkey/Turkiye/Türkiye will match each other.
=> RDISCROWD-6042 backwards compatible turkey spelling

pybossa/cache/task_browse_helpers.py, pybossa/util.py, test/test_util.py
*Issue number of the reported bug or feature request: [RDISCROWD-6207](https://jira.prod.bloomberg.com/browse/RDISCROWD-6207)*
- Remove custom logic for mapping between different spellings of Turkey/Turkiye.
- Remove support for umlaut u in Turkiye
- **Reverts commits:**
- https://github.com/bloomberg/pybossa/commit/da45780b33c689463c54f5597c089f59374f7deb
- https://github.com/bloomberg/pybossa/commit/9633d41458dca3eea2f82d2251b0096a74b4f3fa
Tested locally
=> RDISCROWD-6207 support turkey turkiye

pybossa/view/projects.py, test/test_web.py
*Issue number of the reported bug or feature request: #RDISCROWD-6222*
As a user, I would like to be able to see why no more tasks are available to me even when a project is not yet completed, so that I can understand if there is a problem with the project or if I can work on more tasks.
A typical cause for this is that the project is using the User Preference or Task Queues scheduler and the remaining tasks have preferences configured that are different than the user's.
**Notes**
* Notice that I refactored the "redirect_to_password" check by moving it earlier in the function to avoid needless computation of metrics. This change is unrelated to this feature.
* JSON body shape:
```
"notifications": {
"project_incomplete_info": {
"user_preferences": { …
```
=> RDISCROWD-6222 Show GIGwork users why no tasks are available

pybossa/api/api_base.py, pybossa/api/project.py, pybossa/repositories/__init__.py, test/test_api/test_project_api.py
*Issue number of the reported bug or feature request: #RDISCROWD-6283*
Add a new query parameter to support querying projects by co-owner.
Unit tests pass. Changes also verified manually on localhost.
A project owner is also considered a co-owner because `Project.owners_ids` contains ids for all owners. This means it is sufficient to query `?coowner_id=123` to get all projects where the user is either owner or co-owner.
=> RDISCROWD-6283 - API to obtain projects for user being co-owner.

pybossa/core.py, pybossa/settings_local.py.tmpl, settings_test.py.tmpl
*Issue number of the reported bug or feature request: [RDISCROWD-6484](https://jira.prod.bloomberg.com/browse/RDISCROWD-6484)*
Adds a helpful header to the GIGwork swagger page.
=> add swagger header

.gitignore, pybossa/cloud_store_api/base_conn.py, pybossa/cloud_store_api/connection.py, pybossa/task_creator_helper.py, pybossa/view/fileproxy.py, setup.py, test/test_cloud_store_api/test_connection.py
* add boto3 support
* profiling fileproxy code
* add ability to import csv under bcos v2 buckets via /fileproxy
* add ability for task presenter to load contents from file under bcos v2
=> RDISCROWD-6259: BCOS v2 support under fileproxy

pybossa/api/__init__.py, test/test_api/__init__.py
*Issue number of the reported bug or feature request: [RDISCROWD-6709](https://jira.prod.bloomberg.com/browse/RDISCROWD-6709)*
`num_beams` is not a supported argument for `flan-ul2`. Calling LLM endpoint with it yields a 500 error and the following error:
```
{'error': "ValueError : TGI doesn't support num_beams"}
```
This PR removes `num_beans` argument from llm call.
=> RDISCROWD-6709 update llm call

pybossa/api/__init__.py
Partially reverts change from https://github.com/bloomberg/pybossa/pull/883
- re-adds llm proxies
- refactors `PROXIES` to `LLM_PROXIES` in config for readability
Tested locally
=> add llm proxies

pybossa/core.py, pybossa/settings_local.py.tmpl, test/test_api/__init__.py
*Issue number of the reported bug or feature request: [RDISCROWD-6680](https://jira.prod.bloomberg.com/browse/RDISCROWD-6680)*
On the gigwork swagger page `/apidocs`:
1. Set favicon to match environment
2. Set page title
3. Set top left logo to GIGwork logo
4. Add link on logo to GIGwork home page
Tested locally
**Additional Context**
https://github.com/bloomberg/pybossa-default-theme/pull/444
=> RDISCROWD-6680 update swagger header

pybossa/cache/site_stats.py, pybossa/jobs.py, test/test_cache/test_site_stats.py
- Updated admin project stats usage dashboard to include project_ids and project_names, along with counts.
Re: https://github.com/bloomberg/pybossa-default-theme/pull/449
=> RDISCROWD-7089 Usage stats to include project ids and project names

pybossa/sched.py, test/test_locked_sched.py
- Added error handler for missing task in get_task_id_and_duration_for_project_user.
=> Error handling for missing locked task.

pybossa/cloud_store_api/s3.py, test/test_cloud_store_api/test_s3_uploader.py
=> RDISCROWD-7283: Access buckets with util endpoints

pybossa/api/__init__.py
*Issue number of the reported bug or feature request: RDISCROWD-6956*
add ssl cert path to proxy service request
=> RDISCROWD-6956 add ssl cert path to proxy service request

pybossa/util.py, test/test_util.py
*Issue number of the reported bug or feature request: DRQS 175540044*
Add `None` check for `locations` array in `map_locations` function to prevent error when filtering by user preferences.
```
File "/home/pybossa/pybossa/./pybossa/util.py", line 1426, in map_locations
for location in locations:
TypeError: 'NoneType' object is not iterable
```
Tested locally
=> map_locations None edge case

pybossa/api/__init__.py, pybossa/api/project_locks.py, pybossa/settings_upref_mdata.py.tmpl, pybossa/view/projects.py, test/test_api/test_project_details_api.py, test/test_api/test_project_locks.py
- Added `/api/locks/{project_id}`
- Added unit test.
HTTP GET `/api/locks/1`
```
{
"id": 1,
"short_name": "hello",
"created": "2024-06-17T20:33:11.563072",
"locks": [
{
"user_id": "1",
"task_id": "1",
"seconds_remaining": 3597.541233062744,
"name": "user",
"fullname": "user",
"email": "user@user.com",
"admin": true,
"subadmin": false
}
]
}
```
=> RDISCROWD-7409 Locks API

pybossa/core.py, pybossa/view/account.py, test/test_api/test_project_api.py
*Issue number of the reported bug or feature request: [RDISCROWD-7414](https://jira.prod.bloomberg.com/browse/RDISCROWD-7414)*
separate `DISABLE_TASK_PRESENTER_EDITOR` into 2 flags:
1. `DISABLE_TASK_PRESENTER_EDITOR`: Disable editing the task presenter in the GIGwork UI
2. `DISABLE_TASK_PRESENTER_EDITOR_PAYLOAD`: Disable editing the task presenter through an API request
=> DISABLE_TASK_PRESENTER_EDITOR_PAYLOAD

pybossa/jobs.py, pybossa/run.py, pybossa/settings_local.py.tmpl, test/test_jobs/test_delete_tasks.py
This is an alternative option to delete tasks in bulk. The existing solution is to enable `session_replication_role` that disables triggers on tables having referential integrity defined resulting faster deletes. The new solution under this PR is to  break down large chunk of deletes into smaller batches, introduce delays between batch of deletes to perform bulk delete of tasks.
=> RDISCROWD-7379: Delete task records in batches

pybossa/view/account.py
*Issue number of the reported bug or feature request: DRQS 176080286*
- set taskbrowse bookmark url length limit to 2000
=> RDISCROWD-7501 increase bookmark url length limit

pybossa/api/__init__.py, pybossa/api/project.py, pybossa/contributions_guard.py, test/test_contributions_guard.py, test/test_locked_sched.py, test/test_web.py
* add a new project settings config `reset_presented_time`
* update cache with task cancel information adding new key `pybossa:task_cancelled:user:{0}:task:{1}`
* fix the bug with updating project setting attribute whose value to be updated is to be changed from `True` to `False`
=> RDISCROWD-7554: Reset presented when configured

pybossa/view/projects.py, test/test_web.py
- Bug fix for case where Browse Tasks view=tasklist and no tasks available to no longer show 403 error, redirect to Browse Tasks view.
=> RDISCROWD-6316 Browse TasksList No Tasks Forbidden Error

pybossa/cache/users.py, pybossa/view/projects.py, test/test_web.py
- Update tooltip on keyup and paste (when searching).
- Ignore digits are parenthesis in last names for sorting.
Re: https://github.com/bloomberg/pybossa-default-theme/pull/467
=> RDISCROWD-7561 Sorting users

pybossa/forms/forms.py, pybossa/forms/validator.py
Cloning projects without a password is blocked due to password validation on the frontend. This PR allows empty password strings in the `CheckPasswordStrength` validator when `password_required` is `False`.
Tested Locally
=> allow empty password in validator

pybossa/forms/forms.py
*Issue number of the reported bug or feature request: [RDISCROWD-7659](https://jira.prod.bloomberg.com/browse/RDISCROWD-7659)*
Refactor https://github.com/bloomberg/pybossa/pull/972 after code review.
=> RDISCROWD-7659 password logic in ProjectCommonForm

pybossa/cache/users.py, pybossa/view/projects.py, test/test_cache/test_cache_users.py, test/test_view/test_project_contact.py
- Added logging for get_user.
```
Test Project sanitize_project_owner when no onwer returned and current user is owner. ... 
pybossa:INFO:[2024-10-02 11:27:19,664] owner_sanitized is None after get_user_summary().
project id 1, project name My New Project, owner id 2, owner name user2, current user id 2,
current user name user2, current user authenticated True, is_current_user == owner True [in /mnt/c/Projects/gigwork/pybossa/pybossa/view/projects.py:172]
passed
Test Project sanitize_project_owner when no onwer returned and current user not owner. ... 
pybossa:INFO:[2024-10-02 11:28:14,876] owner_sanitized is None after public_get_user_summary().
project id 1, project name My New Project, owner id 2, owner name user2, current user id 3,
current user name user3, current user authenticated …
```
=> RDISCROWD-7682 Logging for get_user

pybossa/forms/forms.py, pybossa/util.py, pybossa/view/projects.py, test/test_ownership_id.py
*Issue number of the reported bug or feature request: [RDISCROWD-7088](https://jira.prod.bloomberg.com/browse/RDISCROWD-7088)*
- Add endpoint `/<short_name>/ownership_id` to handle project ownership id
- Field name from config
Tested Localy
https://github.com/bloomberg/pybossa-default-theme/pull/469
=> RDISCROWD-7088 add ownership_id to project ownership page

pybossa/repositories/task_repository.py
```
pybossa:INFO:[2024-10-02 17:51:44,275] Delete task profiling. delete request for task 5576, project 2 [in /home/pybossa/pybossa/pybossa/repositories/task_repository.py:205]
pybossa:INFO:[2024-10-02 17:51:44,278] Delete task profiling. Time for self._delete 0.003495 seconds (task 5576, project 2) [in /home/pybossa/pybossa/pybossa/repositories/task_repository.py:211]
pybossa:INFO:[2024-10-02 17:51:44,289] Delete task profiling. Time for self.db.session.commit 0.000372 seconds (task 5576, project 2) [in /home/pybossa/pybossa/pybossa/repositories/task_repository.py:217]
pybossa:INFO:[2024-10-02 17:51:44,292] Delete task profiling. Time for cached_projects.clean_project 0.003754 seconds (task 5576, project 2) [in /home/pybossa/pybossa/pybossa/repositories/task_repository.py:222] …
```
=> No Jira: Record time for task deletion

pybossa/repositories/task_repository.py
Sample logs from local instance comparing total value reported in logs vs manually calculated to confirm they match
```
pybossa:INFO:[2024-10-10 22:59:54,056] Delete task profiling task 5609, project 5 Total time 0.011488 seconds. 
self._delete 0.002237 seconds, element.project 0.006064 seconds, db.session.commit 0.000581 seconds, 
cached_projects.clean_project 0.002240 seconds, self._delete_zip_files_from_store 0.000366 seconds [in 
/home/pybossa/pybossa/pybossa/repositories/task_repository.py:235]
Total time logged                 0.011488 seconds. 
--------------------------------------------
self._delete                      0.002237 seconds, 
element.project                   0.006064 seconds, 
db.session.commit                 0.000581 seconds, 
cached_projects.clean_project …
```
=> delete task logs

pybossa/exporter/export_helpers.py, pybossa/exporter/task_csv_export.py, test/test_jobs/test_export.py
*Issue number of the reported bug or feature request: [RDISCROWD-7364](https://jira.prod.bloomberg.com/browse/RDISCROWD-7364)*
- Update task csv export: when `display_info_columns` is in the request body, filter the `task__info` fields to only contain fields in `display_info_columns`.
tested locally
=> RDISCROWD-7364 custom task export fields

pybossa/api/task.py, test/test_api/test_task_api.py
*Issue number of the reported bug or feature request: [RDISCROWD-7573](https://jira.prod.bloomberg.com/browse/RDISCROWD-7573)*
add project null check after fetching project info in `_preprocess_post_data`
=> RDISCROWD-7573 update error on nonexistent project id in task API

alembic/versions/d4363025a58c_add_dup_checksum_col_to_task.py
Upgrade brings in new column and indexes
```
$ alembic upgrade head
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade c7d7de1f09f6 -> d4363025a58c, add dup_checksum_col to task
```
Downgrade removes new column and indexes
```
$ alembic downgrade c7d7de1f09f6
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running downgrade d4363025a58c -> c7d7de1f09f6, add dup_checksum_col to task
```
=> RDISCROWD-7701: Add dup_checksum col and associated index to task table

pybossa/core.py, test/test_web.py
*Issue number of the reported bug or feature request: [RDISCROWD-7852](https://jira.prod.bloomberg.com/browse/RDISCROWD-7852)*
Add project owner name to 423 error page
https://github.com/bloomberg/pybossa-default-theme/pull/482
=> add project owner to 423

pybossa/view/projects.py, test/test_web.py
*Issue number of the reported bug or feature request: [RDISCROWD-7852](https://jira.prod.bloomberg.com/browse/RDISCROWD-7852)
Redirect to 423 error page when common project API routes are accessed and user does not have access rights.
- `/<short_name>/password`
- `/<short_name>/task/<int:task_id>`
- `/<short_name>/newtask`
- `/<short_name>/tasks/`
- `/<short_name>/tasks/browse`
- `/<short_name>/tasks/settings`
- `/<short_name>/tasks/timeout`
Upon improper credentials. , routes workers could have access to return 423, while routes only admins have access to still return 403 (like `/<short_name>/clone`, `/<short_name>/delete`, etc)
=> RDISCROWD-7852 project routes redirect to 423 when user not allowed

pybossa/jobs.py, pybossa/settings_local.py.tmpl, test/test_jobs/test_export_tasks.py
*Issue number of the reported bug or feature request: [RDISCROWD-7813](https://jira.prod.bloomberg.com/browse/RDISCROWD-7813)*
change behavior for task exports:
- if content size larger than `EXPORT_MAX_UPLOAD_SIZE`, don't upload and send error email
- else if larger than `EXPORT_MAX_EMAIL_SIZE`, upload file and send link in email
- else, file is small, so send as email attachment
=> RDISCROWD-7813 - file size limit

pybossa/view/projects.py
*Issue number of the reported bug or feature request: RDISCROWD-7875*
The authorized services form was randomly appearing and disappearing between page refreshes.
This [line](https://github.com/bloomberg/pybossa/blob/094984e46b05fd94ae155c1bff4e179872748c54/pybossa/view/projects.py#L3694) was overwriting `EXTERNAL_CONFIGURATIONS_VUE` and removing the `authorized_services` key when the user was not an admin. And when another user who was an admin loaded the config, the app would read from the same app context and `EXTERNAL_CONFIGURATIONS_VUE` would not have that key anymore.
Deep copy the config before mutating it.
=> RDISCROWD-7875 - fix bug where config is overwritten

pybossa/model/task.py, pybossa/repositories/task_repository.py, pybossa/task_creator_helper.py, test/test_exporter/test_task_csv_exporter.py, test/test_web.py
* Add column dup_checksum to task model class
* As SHA 256 will be always 64 hex characters, restrict task.dup_checksum to `String(64)`
* Upon generating checksum based on project configuration, set checksum value into task table.
=> RDISCROWD-7704: Update task with checksum value

pybossa/api/__init__.py, pybossa/api/docs/project/project_clone.yaml, test/test_api/test_project_api.py
*Issue number of the reported bug or feature request: [RDISCROWD-7842](https://jira.prod.bloomberg.com/browse/RDISCROWD-7842)*
add routes for cloning a project, with the same functionality as the UI at `/project/<short_name>clone`
1.  POST `/api/project/<short_name>/clone`
2. POST `/api/project/<project_id>/clone`
body:
```
{
copy_users: bool (default= false),
name: str,
short_name: str,
input_data_class: str,
output_data_class: str
password: str
}
```
`name`, `short_name`, `input_data_class`, and `output_data_class` are all required fields.
=> RDISCROWD-7842 add project clone API endpoint

pybossa/core.py, test/test_web.py
*Issue number of the reported bug or feature request: [RDISCROWD-7895](https://jira.prod.bloomberg.com/browse/RDISCROWD-7895)*
- support custom error messages in `abort()` calls
- Many methods already assume that this works and pass strings to abort, like `abort(400, "my custom message")`. Now these will actually get sent to the user and will be helpful when they are working with our API.
Some usage examples:
1. https://github.com/bloomberg/pybossa/blob/main/pybossa/api/__init__.py#L795
2. https://github.com/bloomberg/pybossa/blob/main/pybossa/api/__init__.py#L733
3. https://github.com/bloomberg/pybossa/blob/main/pybossa/api/__init__.py#L772
Tested locally
=> RDISCROWD-7895 custom error messages

pybossa/repositories/project_repository.py, test/test_api/test_project_api.py
*Issue number of the reported bug or feature request: RDISCROWD-7968*
Add `n_gold_tasks` to `/project/<id>/projectprogress` API response
No changes to existing fields `n_completed_tasks` and `n_tasks`
**Example:**
**Request:**
GET `/api/project/50/projectprogress`
**Response:**
```
{
"n_completed_tasks": 1,
"n_tasks": 149,
"n_gold_tasks": 2
}
```
Tested locally
=> RDISCROWD-7968 add n_gold_tasks to projectprogress API

pybossa/api/api_base.py, pybossa/api/task.py, pybossa/cloud_store_api/s3.py
* Added logs to create, update and delete operations
* Added logs to record time it take to load file from storage and perform decryption(if any)
* Example of logs that would be generated with this PR
File load duration
```
pybossa:INFO:[2025-02-23 04:22:40,860] Calling CustomConnectionV2 [in /home/pybossa/pybossa/pybossa/cloud_store_api/connection.py:54]
pybossa:INFO:[2025-02-23 04:22:41,609] get_content_and_key_from_s3. Load file contents gigwork-eng-bcos-dev//9/task_data1.txt duration 0.748837 seconds [in /home/pybossa/pybossa/pybossa/cloud_store_api/s3.py:208]
pybossa:INFO:[2025-02-23 04:22:41,609] get_content_and_key_from_s3. file gigwork-eng-bcos-dev//9/task_data1.txt decryption duration 0.000269 seconds [in /home/pybossa/pybossa/pybossa/cloud_store_api/s3.py:216]
```
Project API …
=> RDISCROWD-7993: Add logs. file load duration. crud activity

pybossa/api/task.py, pybossa/importers/importer.py, pybossa/settings_local.py.tmpl, pybossa/task_creator_helper.py, test/test_api/test_task_api.py, test/test_importers/__init__.py, test/test_importers/test_importer_validation.py, test/test_web.py
Exclude reserved fields from duplicate task check. This is default behavior and applies irrespective of whether duplicate task check has been configured or not.
=> RDISCROWD-7866: Exclude reserved fields from duplicate task check
